### ISSUE TITLE
Add GWZ as a reference layer to map views for Admin users

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#103]
As a logged-in Admin users I would like to be able to toggle the [GWZ layer](https://utahdeq.maps.arcgis.com/home/item.html?id=f8e7cb150f984ac29493bf6b41c26d8b) on/off during the Admin review process, and click on the layer to identify.

**Comment by nathankota** [comment]
[GWZ test layer](https://utahdeq.maps.arcgis.com/home/item.html?id=f8e7cb150f984ac29493bf6b41c26d8b)

**Comment by steveoh** [comment]
Are we adding this to the existing pages for admin users, or will we show the site and inventory locations on a specific admin map that will have the gwz layer?

**Comment by nathankota** [comment]
At first we thought on the regulatory user pages, but now that the idea is to have a separate admin review/approval flow, it should probably be there. We will include it as we sort that out.

**Comment by steveoh** [comment]
Ok i'll edit the description

**Comment by nathankota** [comment]
<edited>

**Comment by nathankota** [comment]
Validated with UIC admins. Layer toggle and identify not necessary.
