### ISSUE TITLE
Firewall request for DDW database

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#104]
This is for the app to communicate with the `utahddw` database to gather water system info from the `wv_water_system_admin_contacts` view if well point(s) intersect the GWPZ layer (#60).

**Comment by nathankota** [comment]
REQ0126401
RITM0176384

**Comment by nathankota** [comment]
The firewall request was rejected due to the requirement of a "specific" source and IP, but the source GCP project does not conform to the format of an IP and, therefore, cannot be entered into the firewall form field. Reached out to Derrek Spencer and Jonathan Foster for guidance on how to submit this cloud-to-state firewall request.

**Comment by nathankota** [comment]
waiting on #109 before resubmitting firewall request

**Comment by steveoh** [comment]
I don't think you need to wait. It should all be able to be done prior to using the dev shared VPC.

**Comment by nathankota** [comment]
what do I enter in the request for the specific source IP?

**Comment by steveoh** [comment]
Ask foster

**Comment by nathankota** [comment]
The shared dts vpc has been added to the google project for the app via INC1558817. Second try for a firewall request is [RITM0178705](https://utah.service-now.com/nav_to.do?uri=sc_req_item.do?sys_id=6ee18f841bbff4900e0f1f09b04bcb7a)

**Comment by steveoh** [comment]
You can close and we can open again if it doesn't work when we test.

**Comment by nathankota** [comment]
RITM0178705 contained the incorrect source IP, which affected #176 and #177. This was resolved via:

New Firewall request [RITM0196543](https://utah.service-now.com/nav_to.do?uri=%2Fsc_req_item.do%3Fsys_id%3Dccfa7e8687ae495002637489cebb35e2%26sysparm_stack%3D%26sysparm_view%3D)

Request to remove the old one is [RITM0196545](https://utah.service-now.com/sc_req_item.do?sys_id=4c9c3a0287ee495002637489cebb354f&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog)
