### ISSUE TITLE
Regulatory Contact on Site Contact page

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#105]
Since we do not require an address for the SER Regulatory Contact, it shows up as `null` values on the Site Contacts page. Address field can be blank for Regulator Contacts.

![image](https://user-images.githubusercontent.com/15659642/138178478-b00cabb5-1ce1-4b36-91bf-721bb754df4e.png)

**Comment by steveoh** [comment]
This was fixed a long time ago.

**Comment by nathankota** [comment]
thank you
