### ISSUE TITLE
Well status update selections

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#113]
Users may update the status of wells for approved inventories. The available status selections are:

- Active
- Abandoned - Approved
- Other (if chosen, the Description field is activated and required)

Add a `Save` button that user must click to enable the change.

**Comment by steveoh** [comment]
Where would the UI for this be?

**Comment by nathankota** [comment]
Somewhere in the inventory subcomponent #111.

**Comment by steveoh** [comment]
Should we move this to a new project or use a label to differentiate it from the normal inventory creation vs post approval editing?

**Comment by nathankota** [comment]
> Should we move this to a new project or use a label to differentiate it from the normal inventory creation vs post approval editing?

Added to new project for Post-Approval Editing

**Comment by steveoh** [comment]
Is this UI acceptable? I'll build the server side part if it's good.

**Comment by nathankota** [comment]
Looks great! 
![image](https://user-images.githubusercontent.com/15659642/236888936-e29dd811-bd8f-49fa-b2a4-461d4ff50318.png)

When modifying to "Other", we'll also need a Description text field like when a new well is added:
![image](https://user-images.githubusercontent.com/15659642/236889190-451ecf4c-dada-481c-a72c-ef908967a26f.png)

Looks like we [thought about](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457352930147375&cot=14) having the "Other" status show up as a link or hover-over in the well table so the description can be viewed. I'll add an issue for that.

**Comment by nathankota** [comment]
@rsparker-utah, note the notification associated with the well status change.

**Comment by nathankota** [comment]
Validation included:
- changing and saving a well status
- seeing a notification (bell) for the change
- changing a status to Other and entering and saving a description
- changing an existing Other description
- seeing notifications for status change to Other, and when just the Other description is edited and saved

**Comment by rsparker-utah** [comment]
This is great! The UI is intuitive and I can confirm the same validations as Nathan mentioned above. 

I did come across a potential glitch/bug(?) when doing the following:

- Select the "modify" icon under well operating status
- Select a new well operating status from the drop down list
- Click the "cancel" button

This does in fact cancel the selection, but leaves the last selected well operating status still visible in the UI which could be confusing for the user. Refreshing the page shows the correct operating status again. This bug/glitch is extremely minor (I would consider it low priority) and I can't it see it happening often, but thought I would mention it in case there is an easy adjustment. 
![Cancel_Button](https://github.com/uic-utah/uic-inventory/assets/49735267/622804ba-9513-40e4-99ad-0b48c41cc0f4)
