### ISSUE TITLE
Highlight selected well and table record

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#117]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3458764515350671634&cot=10)
Select saved/added well point on the map to highlight the associated record in the table, and vice versa (click table record to highlight well point). 
Artistic license may be applied to the selection of the highlight color.

![image](https://user-images.githubusercontent.com/15659642/146436498-19be8ab0-5056-4644-9339-29c4713a0bf8.png)

**Comment by nathankota** [comment]
If this task requires a significant amount of time to complete, another alternative is to enable a hover-over popup on the well points that shows construction/name and operating status.

**Comment by steveoh** [comment]
i've got the table highlighting the graphics. do you think we need the graphics to also highlight the table?

**Comment by nathankota** [comment]
> i've got the table highlighting the graphics. do you think we need the graphics to also highlight the table?

Client thinks it makes sense to do this too.

**Comment by nathankota** [comment]
looks good!
