### ISSUE TITLE
Registration and Sign-in

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#12]
### [Miro page](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457352731357527&cot=14)

New users must:

- Register with Utah ID
- Save additional profile info
    -  organization
    - phone
    - mailing address
    - city
    - state
    - zip

User is logged-in once they create a Utah ID.
App presents the additional profile information to be entered/saved (must be done before they can add sites/inventories). 
Admin receives a notification when new user signs up.

**Comment by steveoh** [comment]
The app creates a basic UIC account after authenticating with UtahID (this is the just in time provisioning thing i've been talking about). What is auto-approval and what does creating a uic account mean?

**Comment by nathankota** [comment]
Doesn't look like login.utah.gov directs _back_ to the UIC app after a UtahID account is created, which is totally fine. As a simple alternative, please open login.utah.gov in a separate browser tab when the _Utah ID_ link is clicked.

![image](https://user-images.githubusercontent.com/15659642/125687353-1ed50270-4255-4e1e-9279-d92533b1fbc1.png)

**Comment by steveoh** [comment]
I think the instructions are the problem. I can make the Utah Id link behave the same as the login button above. But the way I believe it should work is that you click login with or without a utah id account and then follow the instructions to create an account there.

**Comment by nathankota** [comment]
Okay, I see now that if you already have an account and click _Login_ you are directed to id.utah.gov and, once you sign in, it immediately kicks you back to UIC. I also see that the Miro instructions suck and say that you need to create a UtahID then "return to this page". I created a new account to test the process and had to find my way back to the UIC site after going through UtahID account creation. Not a big deal for me, but probably a hassle for a new user. Yes, if you can make the _Utah ID_ link behave the same way in so much as it brings the user back to UIC logged in as soon as they create a UtahID account, that is muito apreciado.

**Comment by nathankota** [comment]
validated
