### ISSUE TITLE
Persistent selectedWells error message

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#121]
The warning/error message in the image below does not go away when a well is selected.

To reproduce:
- Select one well
- Deselect well
- Message appears with “0 wells selected”
- Select a well again
- Message doesn’t go away even though there is a well selected

![image](https://user-images.githubusercontent.com/15659642/146462091-6085cbad-1296-4228-badb-ad1240c520d9.png)

**Comment by nathankota** [comment]
When is this message meant to occur? Will find out different verbiage if it is one that is supposed to guide the user somehow.

**Comment by steveoh** [comment]
> When is this message meant to occur? Will find out different verbiage if it is one that is supposed to guide the user somehow.

Do you have any information to share?

**Comment by nathankota** [comment]
I don't understand the purpose of the error message yet.
