### ISSUE TITLE
Add buttons to edit approved inventory and site

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#132]
Once admin has approved an inventory, limited inventory and site data can be edited by the user who "owns" the data. Add the following edit buttons to the list of sites/inventories. Their functionality will be defined in subsequent issues.
**Site:** `Edit Contacts`
**Approved Inventory:** `Add/Edit Wells`

![image](https://user-images.githubusercontent.com/15659642/147167049-34974943-6cf9-4632-b8ab-399cd10192ad.png)

**Comment by steveoh** [comment]
I'm afraid we are adding too much information to this table. It almost requires you to have a large screen device to see things correctly now. Is there a way to remove the table as the main focus of navigation that you can think of?

**Comment by nathankota** [comment]
I will engage the UIC folks and see what we can come up with.

**Comment by nathankota** [comment]
Closing this and adding new issue since we will not implement these additional buttons.
