### ISSUE TITLE
Inventory completeness icons and links to pages

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#133]
This issue accompanies #111.

The Inventory Completeness indicators/icons should work similarly to the Site completeness indicators/icons. 
- Once an inventory is initiated by entering subclass type and order number, the record appears in the inventory component/list. 
- When **Page Conditions** (from #111) are met, a checkmark appears above the icon
- If any page conditions are not met, there is an 'x' above the icon
- Clicking on an icon navigates to the associated page...

## Completeness Indicators/Icons: 
![image](https://user-images.githubusercontent.com/15659642/147256169-5128eb8d-77dd-4177-8096-450e11826434.png)
**Hover over text:** well subclass & order
**Links to:** Well Inventory page for selected inventory
**Note:** This indicator/icon will always be checked because completing this page is the only way to initiate an inventory. 

![image](https://user-images.githubusercontent.com/15659642/147257176-2b5a0e5a-5676-420e-996b-7266d61a77af.png)
**Hover over text:** regulatory contact
**Links to:** regulatory-contact page for selected inventory
**Note:** This indicator/icon only appears if SER is chosen as the well subclass type on the well inventory creation page.

![image](https://user-images.githubusercontent.com/15659642/147257863-c6cd4b15-355b-4af9-b0b0-95a29f9867b1.png)
 **Hover over text:** well locations
**Links to:** add-wells page for selected inventory

![image](https://user-images.githubusercontent.com/15659642/147258452-11c3bc4c-9051-40c9-aff1-f3b963e2c22f.png)
 **Hover over text:** well details
**Links to:** add-well-details page for selected inventory

![image](https://user-images.githubusercontent.com/15659642/147258577-42000975-2828-481f-bff6-1465db9e5dc9.png)
 **Hover over text:** sign and submit
**Links to:** sign and submit #62 page for selected inventory

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/147795297-1e3f162e-c2ab-44c0-b370-ad21767d269c.png)

These are the icons I have chosen.

I vote that we remove the order # subclass icon, which is the dollar sign, since it is always true and we currently do not allow for that data to be edited. They would have to delete the inventory and start over.

**Comment by nathankota** [comment]
This will be considered complete, and recently-determined changes will be added as new issues, including the removal of the order number icon according to the recommendation below, and how to deal with the agency regulatory contacts for SER wells.

> I vote that we remove the order # subclass icon, which is the dollar sign, since it is always true and we currently do not allow for that data to be edited. They would have to delete the inventory and start over. Right now it is not a link and only taking up space.
