### ISSUE TITLE
Differentiate icons for editable pages, post-approval

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#142]
Need to somehow show that the Site Contact and Well Locations icons can be clicked to edit _some_ info on those pages once inventory status is Approved. Some ideas to differentiate them from the other icons are:

- make them a different hue of gray
- make them a different color
- add an outline of a different color
- make them a different size
- add the words "View/Edit" under them
- change hover-over popup text to include the word Edit
- add an adjustment icon with increased transparency on top of them? 
![image](https://user-images.githubusercontent.com/15659642/149411882-eeb3b64c-0ce6-4cf6-abe7-26e3f8bdca21.png)

**Comment by steveoh** [comment]
Are the rules for what is editable based on status defined in an issue already?

**Comment by nathankota** [comment]
They are not. It is forthcoming.

**Comment by nathankota** [comment]
ref: #143
