### ISSUE TITLE
Add link to UIC inventory site in inventory submission email(s)

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#144]
Add link to prod UIC inventory site in inventory submission emails (submitter and admin).

**Comment by steveoh** [comment]
Can you use a more descriptive word beside wonky to describe the problem?

**Comment by nathankota** [comment]
Not sure what was up before, but it's working fine now. I'm going to change this issue.

**Comment by nathankota** [comment]
@rsparker-utah 
Responding to your question from the [prioritization sheet](https://docs.google.com/spreadsheets/d/1UE9R5UVKaAqi05JgYmXLP5oKgHOZPE-dp4Kmmi9fhcM/edit?pli=1#gid=0):
> Clarification on this item, what does the link mentioned in issue# 144 do? 

It would be a direct link to some page of the submitted well inventory, for example [Site 71, Inventory 136](https://uic-inventory.dev.utah.gov/site/71/inventory/136/add-wells). I think it's a low priority, and maybe we just provide a link to the default page, or no link at all.

**Comment by nathankota** [comment]
We are not generating auto-emails in the first production release, and will be including a link to the inventory review page in the ABR letter.
