### ISSUE TITLE
Regulatory Contact for SER inventories

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#145]
It is likely that a submitter will know who the DEQ regulatory contact will be for their SER site+inventory when they are entering site contact information. Rather than make them wait until the well inventory to enter the SER contact it is proposed to:
- [x] Add a boolean flag in the database for SER contact
- [x] Add a toggle on the Site's Add Contact form with text: _Regulatory contact providing primary oversight for subsurface environmental remediation (SER) wells_
    - [x] When toggle is engaged, the form changes to show the fields required for the SER Regulatory Contact
    - [ ] If they add a Reg Contact, the form changes back to default, without the toggle engaged
- Even if they complete the SER Reg Contact on the Site Contact page, it is still part of the workflow for an SER well inventory, and 
    - the previously-added SER contact(s) appear on the Regulatory Contacts page during the inventory workflow, and they can simply click `Next`
    - it satisfies the completion requirement for that page and the SER contact icon
- If they do not complete the SER Contact on the Site Contact page, they must enter it during the inventory workflow
- [x] Completeness check will operate on the boolean flag

**Comment by steveoh** [comment]
Is this along the lines of what you had in mind. Or would it make sense to be more inline with the form?
![image](https://user-images.githubusercontent.com/325813/149251613-59aa5260-5b7e-49a5-90e5-a3acc8e3bf6a.png)

**Comment by nathankota** [comment]
That is exactly what I had in mind. I had some uncertainty about where to put it too, but I like the idea of it being in-line with the form and more visible. I hacked together the description quickly, and will get a better one from UIC .

**Comment by nathankota** [comment]
Here is the text UIC admins would like to include, in addition to the `SER Contact` label for the toggle:
_Primary regulatory oversight of subsurface environmental remediation projects is provided by programs and agencies other than the UIC Program and DWQ. Enter the oversight agency for the remediation project and provide the name and contact information for the project manager in that agency._

**Comment by nathankota** [comment]
I like that approach better and have proposed the following text to UIC admins to strike a balance between their previous text and keeping it as a question that works with the toggle. Once we land on the correct question, it can simply replace the text in the above screenshot.

_Is this a Department of Environmental Quality contact providing primary regulatory oversight for subsurface environmental remediation?_

**Comment by nathankota** [comment]
This piece looks good and is working. I came across a little issue when testing that I will submit separately.
