### ISSUE TITLE
Approved-inventory edit notifications

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#148]
As an Admin, I need "bell" notifications when an `Approved` inventory has edits made to the site contacts and/or wells. All of these notifications should have the following content, plus additional content for the scenarios below.

### For all edit notifications, include:
- date of change
- time of change
- initials or name of user who edited 
- link to the edited page
- icon for read/unread
- icon to delete notification

(if not including the user name/initials shortens the notification significantly, then removing the name/initials will be considered)

### Site Contacts edits
Regardless if a contact was added or deleted, I just need to know that a change occurred. Notification should also include a message such as:
_NK edited contacts for approved site 43_ 

### Well Status edits
Include in the message the initial status and the changed status, such as:
_NK changed well status from `Active` to `Abandoned - Approved` for inventory 22_

### New wells added
Include in message that new well(s) were added:
_NK added new well(s) to inventory 37_

**Comment by steveoh** [comment]
It would be a lot less work for the well status to keep the notification pattern similar to contacts  and new wells 

e.g. _NK edited teh well status for inventory 22_

**Comment by nathankota** [comment]
I like keeping it in the same pattern too. It is also important for admins to know what the status was changed from. Right now we are not thinking an approval process is needed for edits, hence the expanded notification for well status, unless we can come up with another simple way to indicate the former status.

> It would be a lot less work for the well status to keep the notification pattern similar to contacts and new wells
> 
> e.g. _NK edited the well status for inventory 22_

**Comment by steveoh** [comment]
change tracking or audit trails will be a larger feature. Do you know if it's only for a couple of fields or if there will be a larger requirement to view changes to sites and inventories?

**Comment by nathankota** [comment]
The only field an audit trail is needed for is well status. Change tracking and notification is requested for site contacts and new wells and details. I will specify those fields when back in front of my computer.

**Comment by nathankota** [comment]
The only field an audit trail is needed for is well status, which also requires some sort of simple editing interface for only that field for an approved inventory.  (new issue coming up)

As long as the rules can be enforced for site contacts (must have one of the required types, and must have ser contact if there is an ser well inventory), then we really just need a notification when the Add or Delete buttons are clicked on the Site Contacts page when there is an approved well inventory associated with that site. Therefore, if a owner/operator (or ser contact) needs to be changed, they'll have to add the new one first, then delete the old. 

Similar situation for new wells. If they Add a new well when inventory status = approved, we just need a notification for that, and to ensure they enter well details for any new well(s). They will not be able to delete approved wells, so no notification is needed for that.

**Comment by nathankota** [comment]
@rsparker-utah what do you think about the discussion above, related to the simplification of well status change notifications? 

> It would be a lot less work for the well status to keep the notification pattern similar to contacts and new wells
> 
> e.g. _NK edited the well status for inventory 22_

**Comment by steveoh** [comment]
I don't think this has anything to do with database importing as these are app notifications. I might recommend making each of the 3 a separate issue since they are 3 separate features. That would make it simpler to notice that I've completed one of them.

**Comment by nathankota** [comment]
closed in favor of #253 , #254 , #255
