### ISSUE TITLE
SER contact completeness confirmed before contact added

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#151]
### Observed
- Site Contacts list for Blackhawk Subdivision only includes the Owner/Operator
- Created new SER inventory by choosing the subclass type and adding an inventory order number
- Advanced to SER contacts page, but didn't enter a new contact
- Went back to sites+inventory table and the regulatory contact icon was indicated as complete

![image](https://user-images.githubusercontent.com/15659642/150831514-6eeae204-a625-4fb0-815a-3911bf0a37e2.png)

### Expected
- Create new SER inventory with no regulatory contacts entered and the regulatory contact completeness icon should indicate that a contact is still needed.

**Comment by steveoh** [comment]
We talked about this last week. SER contacts are assigned to a site so every SER inventory will already have a regulatory contact.

**Comment by nathankota** [comment]
This site did not have a SER contact.

> Site Contacts list for Blackhawk Subdivision only includes the Owner/Operator

**Comment by nathankota** [comment]
validated! tested on a couple projects and looks good
