### ISSUE TITLE
Add a new UICWellSWPZ table to the UIC database

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#159]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457360912867982&cot=14) - highlighted rows

Since a well can overlap multiple groundwater zones in different water systems (#60), there will need to be a new 1:many table in the UIC database to store those contacts.  Proposed table name can be changed by UIC admins, depending on their preference.

**Proposed Name:** UICWellSWPZ
**Field 1:** SystemName
**Field 2:** ContactName
**Field 3:** ContactEmail

**Comment by nathankota** [comment]
Relationship class still to be created between Well table and this new table.

**Comment by nathankota** [comment]
Sent some links to hopefully guide this:
[Relationship classes toolset overview](https://pro.arcgis.com/en/pro-app/latest/tool-reference/data-management/an-overview-of-the-relationship-classes-toolset.htm
)
[Create relationship classes tool](https://pro.arcgis.com/en/pro-app/latest/tool-reference/data-management/create-relationship-class.htm)

**Comment by rsparker-utah** [comment]
@nathankota 
@Brianna81 

The following has been added to the Production UIC Geodatabase:

New Table: UICWellSWPZ

Fields in the new UICWellSWPZ Table:
- OBJECTID
- GlobalID
- GUID
- Well_FK
- SystemName
- ContactName
- ContactEmail
- Comments

Additionally, a new one to many relationship was added from UICWell to UICWellSWPZ.

**Comment by nathankota** [comment]
@rsparker-utah it sounds like this task is complete?

**Comment by rsparker-utah** [comment]
@nathankota Yep, this one is complete and can be closed. Thank you!
