### ISSUE TITLE
Admins can change the Inventory Subclass during review

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#160]
As and admin, while reviewing a submitted inventory I would like to be able to change the Inventory Subclass. I would like to be able to select from a list of all of the records in the `UICWellSubClassDomain` table with a code that begins with 5. I do not need to see the domain code, but do need to see the description.

![image](https://user-images.githubusercontent.com/15659642/152446709-754c6768-903f-400e-9578-90b29b0c29c0.png)

**Comment by steveoh** [comment]
FYI: The app does not have access to the UICWellSubClassDomain so I will snapshot the available options from a drive sheet.

**Comment by nathankota** [comment]
ref #179

I like it! I did notice it displays the code rather than description of the saved selection, except for the two in the list that have been well subclass type selections all along (Storm water drainage and SER). Also noticed that if any of the newer types are selected, the Site cannot be opened/expanded to see the associated inventories (a blank page appears). Are those the bugs you recognized too?

**Comment by steveoh** [comment]
Yes, those are the main ones.

**Comment by nathankota** [comment]
This is working as expected with a couple "bugs" that will be separated into new issues
