### ISSUE TITLE
Show SWPZ status in admin review

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#161]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3458764518128096830&cot=14)
As an Admin, when I am reviewing an inventory I would like to see the Source Water Protection Zone intersect results.

ref #60

**Comment by nathankota** [comment]
### Waiting for UIC feedback on the following comments, about whether they would like to pursue the bottom two scenarios.

Looks good when both are negative... 
[Garden City Growlers](https://uic-inventory.dev.utah.gov/review/site/61/inventory/107)
Site: 61
Inventory: 107
![image](https://user-images.githubusercontent.com/15659642/154325016-5281d133-771e-4e08-a216-f420c0036954.png)

and GWZ is negative and ARDA is positive
[Lambs in Lamb's](https://uic-inventory.dev.utah.gov/review/site/48/inventory/106)
Site: 48
Inventory: 106
![image](https://user-images.githubusercontent.com/15659642/154325292-0ef39976-39b0-449a-a9ea-84c37ff5821a.png)

If it's not too much trouble it might also be interesting to see color for ARDA when...

 GWZ and ARDA are positive (ARDA would also be green)
[The Links at Meadowbrook - Storm water drainage wells](https://uic-inventory.dev.utah.gov/review/site/60/inventory/105)
Site: 60
Inventory: 105
![image](https://user-images.githubusercontent.com/15659642/154327631-404810d3-f45a-483e-914c-e3779f1012f8.png)

and when GWZ is positive and ARDA is negative (ARDA would be red)
[Park Ave Silver Mine - General](https://uic-inventory.dev.utah.gov/review/site/62/inventory/109)
Site: 62
Inventory: 109
![image](https://user-images.githubusercontent.com/15659642/154327922-439e7a02-92b9-4c2e-af23-abad77fc676e.png)

**Comment by steveoh** [comment]
in #60 it says to ignore ARDA when GWZ is true so i made it grey.

**Comment by nathankota** [comment]
Although not critical, UIC admins think it would be helpful to also see the color for the ARDA condition (green==true, red==false) when GWZ is true.

**Comment by steveoh** [comment]
You'll have to update the codes to implement this. Y doesn't denote if ARDA is available or not.
