### ISSUE TITLE
Add warning label during review

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#162]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3458764518179063803&cot=10)

As an Admin, if I find there is something wrong with an inventory during the review process I would like to click a "warning"/exclamation point icon to enable it as a warning label for that inventory to serve as a reminder that something is awry and I need to contact the responsible party, or take further action. For fun, perhaps enabling this warning label can highlight the background of the inventory review page to make it more obvious.

**Comment by steveoh** [comment]
Do we want to send mail right from here?

**Comment by nathankota** [comment]
> Do we want to send mail right from here?

Good question. We had discussed the label as enough, but obtaining UIC admin feedback about this possibility.

**Comment by nathankota** [comment]
> Do we want to send mail right from here?

This feature is not needed in the app. UIC admins will email the proper contacts manually.

**Comment by steveoh** [comment]
How does something like this look for creating the flag. And then I'll work out some UI to show when a flag is active. Are you working out the way to resolve a flag or is that up to me?

https://user-images.githubusercontent.com/325813/156057480-5a85dcfd-6858-419a-967d-99a586647e6b.mp4

**Comment by nathankota** [comment]
Yes, this is great, and thank you for the idea so far for resolution: 
<img width="924" alt="image" src="https://user-images.githubusercontent.com/15659642/156064706-39b5c627-e2ef-467d-8ccc-ba21d7014c83.png">

**Comment by nathankota** [comment]
This piece works well. Other tasks around this feature will be included in new issues.
