### ISSUE TITLE
Generate Site+Inventory Report

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#165]
When the _Print_ button is clicked during admin review:

- Inventory summary report opens in new browser tab
- Report is similar to Inventory Review page, and must show all the text for the well details (i.e. construction details, injectate characterization, etc.)
- Any uploaded files by user must be appended to the summary report
- Ability to print from browser or download as pdf
- Print function is available at any time from the status button for the inventory record, e.g. 
![image](https://user-images.githubusercontent.com/15659642/227631875-093c44eb-93df-49a6-8844-8c41c2cd184d.png)

**Comment by nathankota** [comment]
@Brianna81 
Can you think of anything else that needs to happen here?

**Comment by Brianna81** [comment]
I think that covers it, nothing else comes to mind.

**Comment by steveoh** [comment]
How do you want doc/docx to be appended to the report?

**Comment by nathankota** [comment]
Damn good question. Could it prompt auto-download of them?

**Comment by nathankota** [comment]
Client agrees auto-download would be okay, if that is a possibility.

**Comment by steveoh** [comment]
> Ability to print from browser or download as pdf

Can we delegate to the browsers for printing to a printer or to a pdf?

**Comment by nathankota** [comment]
> > Ability to print from browser or download as pdf
> 
> Can we delegate to the browsers for printing to a printer or to a pdf?

Yes

**Comment by steveoh** [comment]
Check out the review page when you hit ctrl+p to print or file > print. 

This allows you to select save to pdf or choose a printer and I think it looks pretty good.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/325813/161172316-1d8c83b8-c895-4e7e-96be-8b4459779e59.png">

**Comment by nathankota** [comment]
> Check out the review page when you hit ctrl+p to print or file > print.
> 
> This allows you to select save to pdf or choose a printer and I think it looks pretty good.

I agree it looks quite good, but I am noticing that the maps tend to get cut off and not show the wells and site boundary, e.g.

![image](https://user-images.githubusercontent.com/15659642/162270061-f264fc06-0b59-4c0d-8a70-26622e1f172a.png)

**Comment by steveoh** [comment]
We're not going to have control over the page breaks since it's a dynamic template based on the number of wells and water system contacts. 

The graphics missing is definitely a problem I did not notice.

**Comment by steveoh** [comment]
Auto download is kind of odd especially if there are multiple files. It makes more sense to me if they download the attachments separately.

**Comment by nathankota** [comment]
> Auto download is kind of odd especially if there are multiple files. It makes more sense to me if they download the attachments separately.

UIC team is working to specify the approval process more precisely, including how they envision accessing and downloading attachments. I am going to close this issue and create new ones as more details emerge, and based on the existing report feature.
