### ISSUE TITLE
Approval email subject and text

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#169]
@Brianna81 What would you like the subject line and email text to be for the inventory approval email, which will also contain the ABR letter+inventory report as an attachment (#168)?

> Subject line: Class V Injection Well Authorization by Rule - `Site Name`
> 
> Email text:
> 
> Hello,
> 
> Attached is the Authorization by Rule letter for the Class V UIC injection well(s) at a site that you are listed as a contact for. This letter is your confirmation of inventory/registration with the Utah Division of Water Quality. If you have any questions please contact Brianna Ariotti at (801) 536-4351.

**Comment by Brianna81** [comment]
Let's go with this for now.....I'm open to suggestions and/or tweaking.....

**Subject line:**  Class V Injection Well Authorization by Rule - **(If possible can we include the site name here?)**

So it would look like this:  Class V Injection Well Authorization by Rule - ABC Inc.

**Email text:**

Hello, 

Attached is the Authorization by Rule letter for the Class V UIC injection well(s) at a site that you are listed as a contact for.  This letter is your confirmation of inventory/registration with the Utah Division of Water Quality.  If you have any questions please contact Brianna Ariotti at (801) 536-4351.

**Comment by nathankota** [comment]
Referenced in #168.
