### ISSUE TITLE
Access to Inventory Review page when status is Approved

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#170]
- As an Admin, after I have approved an inventory and the status changes to 'Approved' on the table record (#168), I would still like to be able to click on `Approved` and have the inventory review page open.
- I can Reject or Approve again, if necessary, for example in the case where admin edits the inventory data, then re-approves.

**Comment by nathankota** [comment]
@rsparker-utah Is the second part of this true?
> * As an Admin, after I have approved an inventory and the status changes to 'Approved' on the table record ([Final Inventory Approval #168](https://github.com/uic-utah/uic-inventory/issues/168)), I would still like to be able to click on `Approved` and have the inventory review page open.
> * I can Reject or Approve again, if necessary, for example in the case where admin edits the inventory data, then re-approves.

**Comment by rsparker-utah** [comment]
@nathankota Mark and I had a chat about this and we felt that the statement "**_I can Reject or Approve again, if necessary, for example in the case where admin edits the inventory data, then re-approves._**" is still true. The one caveat is that we aren't  sure what the original use case was behind this statement; however, we figured this functionality would allow for some flexibility/protection in the event that a mistake was noticed after approving the application.

**Comment by nathankota** [comment]
yes, I think it would be in the case that a mistake was made during approval, for example, if the wrong subclass was chosen.

**Comment by nathankota** [comment]
closing in favor of new issues that will describe the approval process
