### ISSUE TITLE
Rejected inventory email subject and text

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#174]
@Brianna81 What should the subject line and email text be when an inventory is rejected? 

> Subject: UIC Class V Inventory Submittal Rejected - Site Name

> Email Text: Your recent UIC Class V inventory submittal with the Utah Division of Water Quality has been rejected. If you have any questions please contact Brianna Ariotti at (801) 536-4351.

**Comment by steveoh** [comment]
This is in the admin project but it seems like you are asking what the email will look like for the regulated community. Are we wanting to send mail to the other admins that a project was cancelled?

**Comment by nathankota** [comment]
Added to Admin project b/c it must be initiated by Admins (#173), but it could be moved if better suited elsewhere. You raise a good question about whether other admins need to be notified. It was not on our [notification event table](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457356844117441&cot=14), but I will confirm.

**Comment by nathankota** [comment]
> Are we wanting to send mail to the other admins that a project was cancelled?

Negative

**Comment by Brianna81** [comment]
**Subject:** UIC Class V Inventory Submittal Rejected - _Site Name_

**Email Text:**   Your recent UIC Class V inventory submittal with the Utah Division of Water Quality has been rejected.  If you have any questions please contact Brianna Ariotti at (801) 536-4351.

**Comment by nathankota** [comment]
This is referenced in #173.

**Comment by steveoh** [comment]
Should all of the contacts be in the TO of the email?

**Comment by nathankota** [comment]
@Brianna81...

> Should all of the contacts be in the TO of the email?

**Comment by nathankota** [comment]
> Should all of the contacts be in the TO of the email?

Yes, according to bullet point 2, ref [173](https://github.com/uic-utah/uic-inventory/issues/173#issue-1137990512)

**Comment by nathankota** [comment]
Validated using my work and a personal email as contacts.

**Comment by steveoh** [comment]
> Yes, according to bullet point 2, ref [173](https://github.com/uic-utah/uic-inventory/issues/173#issue-1137990512)

Bullet 2

> An email is sent to all of the Site contacts

FYI That does not say how they should receive the email. e.g. each individually, blind copied, etc.

**Comment by nathankota** [comment]
![image](https://user-images.githubusercontent.com/15659642/156666477-fc52094b-a457-41bc-9ac0-9c8f6a774029.png)
