### ISSUE TITLE
Edit site contact 

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#18]
A user may edit or add Site contacts after a site+inventory has been approved.

**Comment by steveoh** [comment]
@nathankota is this a duplicate of #253?

**Comment by nathankota** [comment]
closed in favor of #253

**Comment by steveoh** [comment]
@nathankota Is it possible to edit or add site contacts to an approved inventory now?

**Comment by nathankota** [comment]
The approval workflow is still WIP b/c of the pending decisions around the FacilityID and ABR letter, but are there some inventories that have been assigned the status of Approved? Perhaps the following?

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/5d8be18a-6d88-4b20-88cf-4fb7aedcea01)

**Comment by steveoh** [comment]
Good point, I don't think anything has made it past submitted

**Comment by nathankota** [comment]
We're no longer doing post-approval editing
