### ISSUE TITLE
Differentiate ARDA when GWZ is positive

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#180]
This would require another code in the database because `Y` doesn't denote if ARDA is available or not.

It could be helpful to see color for ARDA when...

 GWZ and ARDA are positive (ARDA would also be green)
[The Links at Meadowbrook - Storm water drainage wells](https://uic-inventory.dev.utah.gov/review/site/60/inventory/105)
Site: 60
Inventory: 105
![image](https://user-images.githubusercontent.com/15659642/154327631-404810d3-f45a-483e-914c-e3779f1012f8.png)

and when GWZ is positive and ARDA is negative (ARDA would be red)
[Park Ave Silver Mine - General](https://uic-inventory.dev.utah.gov/review/site/62/inventory/109)
Site: 62
Inventory: 109
![image](https://user-images.githubusercontent.com/15659642/154327922-439e7a02-92b9-4c2e-af23-abad77fc676e.png)

_Originally posted by @nathankota in https://github.com/uic-utah/uic-inventory/issues/161#issuecomment-1041961642_

**Comment by steveoh** [comment]
Do we want to create another code for the app database to show this visually but only store the Y in the uic database?

**Comment by steveoh** [comment]
I created a `Y+` and a `Y-` that will have to be dealt with during ingestion to the UIC database. This allows the application to now show colors for both types. Existing well values will need to be ignored for testing. It's probably best to submit new inventories.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/325813/155422315-497ab1f5-ea5a-4178-a97c-b8cb2b24ac14.png">

**Comment by nathankota** [comment]
Validated with:

GWZ and ARDA are positive
[The Links at Meadowbrook - Storm water drainage wells](https://uic-inventory.dev.utah.gov/review/site/60/inventory/113)
Site: 60
Inventory: 113
![image](https://user-images.githubusercontent.com/15659642/156653012-9a20b3a2-526a-4f51-a9a4-c3c0d2a1b0c9.png)

GWZ is positive and ARDA is negative
[Park Ave Silver Mine - General](https://uic-inventory.dev.utah.gov/review/site/62/inventory/114)
Site: 62
Inventory: 114
![image](https://user-images.githubusercontent.com/15659642/156653790-3fe1374d-5c38-4a4b-b558-4762c7749a05.png)
