### ISSUE TITLE
Flagged inventory indicator

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#187]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3458764520050873072&cot=14)

Add some sort of indicator on the inventory list to show that an issue flag has been added to an inventory, also since admins would like to be able to filter for them (#153).

**Comment by steveoh** [comment]
This needs to be done for the edocs numbers also.

**Comment by nathankota** [comment]
👍
