### ISSUE TITLE
Well attachment links are not wired up

### ISSUE THREAD

**Issue by steveoh** [uic-utah/uic-inventory#188]
On the review page the links for well attachments go to a route that does not return data

**Comment by nathankota** [comment]
For reference, the "_attachment_" links:

![image](https://user-images.githubusercontent.com/15659642/156651575-8094b9d9-d433-4018-9277-c28d99649682.png)

**Comment by steveoh** [comment]
Attachments uploaded after today will be fetched properly

**Comment by nathankota** [comment]
Looks great! PDF's, png's open in new browser tab, docx's download when clicked, etc. Tested on https://uic-inventory.dev.utah.gov/review/site/48/inventory/125.
