### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by steveoh** [uic-utah/uic-inventory#200]
Explain how the data the app collects is used.

**Comment by nathankota** [comment]
Is the privacy policy expected to be available (via a link or something) on all the app pages?

**Comment by steveoh** [comment]
i don't know

**Comment by nathankota** [comment]
Engaged client to find out what they may have in place for other apps, how they'd like to handle this, and if there is a record set and retention schedule already in place for UIC data.

**Comment by nathankota** [comment]
@rsparker-utah: can you check with your web team, and possibly even DEQ executive team and/or AGs to see if there are any recommendations on how to proceed? The standard utah.gov policy is [here](https://www.utah.gov/support/privacypolicy.html), but it does not address users being able to delete their accounts (#199), and what happens to the data in that situation; which is something that needs to be considered.

**Comment by rsparker-utah** [comment]
@nathankota Certainly, I'll look into this and get back to you asap.

**Comment by rsparker-utah** [comment]
@nathankota I was able to chat with both our DWQ records officer as well as our DEQ Data Management Specialist (who oversees privacy/data management for the department) regarding privacy policy and data retention. Here are the key takeaways from my chats:

- Currently, there is no DEQ specific privacy policy. There is one in the works, but it likely won’t be ready/available for a few years while more guidance comes from gov ops. 
- DWQ has a records retention policy (#[81505](https://axaemarchives.utah.gov/cgi-bin/appxretcget.cgi?WEBINPUT_RUNWHAT=HTML_1SERIES&WEBINPUT_BIBLGRPC_RID=81505&A=B)) pertaining to the UIC program. In chatting with our Data Management Specialist, there should be a mechanism to store this data according to the aforementioned retention policy, even if a user deletes their account. 

In addition, our data management specialist recommended including a statement within the application explaining the reason we're asking for the UIC Inventory information. Our current paper forms have the following explanation text that we could likely use:

"Owners or operators of all Class V injection wells, existing and new, must submit inventory information according to Section [R317-7- 6.4(C)](https://adminrules.utah.gov/public/rule/R317-7/Current%20Rules) of the Utah Administrative Rules for the Underground Injection Control Program. Required information includes: facility name and location; name and address of legal contact; ownership of facility; nature and type of injection wells; and operating status of injection wells. The Utah UIC Inventory Information Form is designed to assist owners or operators to comply with this requirement, to collect sufficient information regarding the injection activity such that authorization-by-rule status can be assessed, and to coordinate UIC Program regulatory action with other agencies having regulatory authority over the subject facility. Inventory information must be submitted prior to injection for new wells. 

**This submission does not relieve the applicant of any liability for ground water cleanup or any claim for resource damage if ground water contamination is traced to the injection wells shown on this form. Nor does authorization-by-rule under the UIC Program relieve the applicant, in any way, of obligations to comply with other applicable regulatory requirements, or to obtain other necessary applicable permits or authorizations from local or other agencies. The applicant may contact the local health department for compliance with local requirements**."

The above text looks to be the same across all of the existing paper forms. For example, see page 4 of the [Storm Water Drainage Inventory Form](https://documents.deq.utah.gov/water-quality/ground-water-protection/underground-injection-control/DWQ-2018-000356.pdf) under the "Class V Inventory Information Forms" section on our [UIC forms and Applications Page](https://deq.utah.gov/water-quality/forms-and-applications-utah-underground-injection-control-uic-program).

**Comment by nathankota** [comment]
@rsparker-utah Where should we include this text on the inventory app, or is it somewhere else on a DEQ website that we could link to? The default inventory app page could be an option if it doesn't already exist somewhere else.

**Comment by nathankota** [comment]
@rsparker-utah This looks good to me. One thing we'll need to change is the date, or just not include it at all?

> As of **_August 15, 2021_** all Class V injection well inventory information forms must be submitted via online web form.

**Comment by steveoh** [comment]
> I removed the section from the original text stating "Required information includes: facility name and location; name and address of legal contact; ownership of facility; nature and type of injection wells; and operating status of injection wells" with my reasoning being that the app will require/collect this information by default.

The idea with a privacy policy is to explain why these pieces of data are collected, how they are used, and who they are shared with.

**Comment by rsparker-utah** [comment]
Thank you both for the comments. I'm fine omitting the date on the homepage. Here is a reworded example based on the comments:

"Owners or operators of all Class V injection wells, existing and new, must submit inventory information according to Section [R317-7- 6.4(C)](https://adminrules.utah.gov/public/rule/R317-7/Current%20Rules) of the Utah Administrative Rules for the Underground Injection Control Program. Required information includes: facility name and location; name and address of legal contact; ownership of facility; nature and type of injection wells; and operating status of injection wells. This online web form is designed to assist owners or operators to comply with this requirement, to collect sufficient information regarding the injection activity such that authorization-by-rule status can be assessed, and to coordinate UIC Program regulatory action with other agencies having regulatory authority over the subject facility. Inventory information must be submitted prior to injection for new wells.

To submit, you must first create a [Utah ID](https://uic-inventory.dev.utah.gov/api/login) account and provide UIC user profile information. Please visit Utah ID to register with Utah ID and then return to this page to login and complete your profile. If you already have a Utah ID account you may login using the link above. Once you have an account you will be able to:

- Submit Class V UIC inventory information forms
- Check inventory form status
- Update well operating status
- Add new wells to existing facilities
- View previous authorizations

**This submission does not relieve the applicant of any liability for ground water cleanup or any claim for resource damage if ground water contamination is traced to the injection wells shown on this form. Nor does authorization-by-rule under the UIC Program relieve the applicant, in any way, of obligations to comply with other applicable regulatory requirements, or to obtain other necessary applicable permits or authorizations from local or other agencies. The applicant may contact the local health department for compliance with local requirements.**"

Updated mock up:
![image](https://user-images.githubusercontent.com/49735267/233163657-0f9e6a2e-a3f7-4e80-aef8-e7f059a8a05d.png)
