### ISSUE TITLE
User/account Management

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#203]
- Assign admin users upon account creation
- ~Notification email when new user signs up (?)~
- Switch user roles (public vs admin)
- what else?

**Comment by steveoh** [comment]
We already create notifications when people sign up. Are emails desired also?

**Comment by nathankota** [comment]
> We already create notifications when people sign up. Are emails desired also?

Good catch. No, and email is not required and this has been removed.

**Comment by steveoh** [comment]
I'm going to close this as it's covered by #207 #209 and #208 . Feel free to re open if this is a mistake.
