### ISSUE TITLE
Maintain well to SWP contact for transfer to UIC database

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#205]
The app assesses each well for an intersection with [groundwater zones](https://utahdeq.maps.arcgis.com/home/item.html?id=88293a87e2954112979e420222ffe3d9), then fetches the water system contact info (#177). Need to keep the relationship of well to contact info to transfer to UIC database.

**Comment by steveoh** [comment]
Are you planning to create issues for every relationship that will be written to the uic database? Otherwise this seems a bit redundant.

**Comment by nathankota** [comment]
> Are you planning to create issues for every relationship that will be written to the uic database? Otherwise this seems a bit redundant.

No. Relationships can be defined as the data transfer process is defined.
