### ISSUE TITLE
Add "User management" link to header

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#208]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3458764521656283384&cot=14)

Add a link for "User management to the header that only logged-in Admins can see/access.

**Comment by steveoh** [comment]
Do we want to hide the contact us for admin users?

**Comment by nathankota** [comment]
> Do we want to hide the contact us for admin users?

Good question. I thought it was okay to keep it, but will find out if the clients prefer your suggestion.

**Comment by nathankota** [comment]
Validated, and will open a new issue if they want to hide the "Contact Us" link for admins.
