### ISSUE TITLE
Create new site - overview

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#22]
As a logged-in regulatory community user when I click the `Create new site` button (#13), it will 

- Kick to the [Site Info page](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457352845392855&cot=14)
- I must complete all fields on that page and define the site geography and boundary in order to save the site

**Comment by steveoh** [comment]
Should that be extracting land ownership from a map? If not what options would you like to be available in that select box>
