### ISSUE TITLE
Create ABR letters

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#223]
@rsparker-utah

Create specific ABR letters for each well type (rather than an all-encompassing, editable one #167).

**Comment by rsparker-utah** [comment]
@nathankota I've been exploring potential ways to make a more generic/standardized ABR template, but it seems like there are too many nuances between the different well types to have a single generic document. What options do we have assuming a generic/standardized template isn't possible? 

Would it be possible for us to create a separate specific template for each of the class V well types that the app references based on the type of well selected in the inventory submission? For example, if the "Storm water drainage wells" type was selected, the app would reference a template specifically made for Storm water drainage wells. Similarly, if the "Subsurface environmental remediation wells" type was selected, the app would reference a template specifically made for SER wells and so forth.

**Comment by nathankota** [comment]
Good idea, and this is the direction we will go. Issue title and initial comment edited to reflect this. 

> @nathankota I've been exploring potential ways to make a more generic/standardized ABR template, but it seems like there are too many nuances between the different well types to have a single generic document. What options do we have assuming a generic/standardized template isn't possible?
> 
> Would it be possible for us to create a separate specific template for each of the class V well types that the app references based on the type of well selected in the inventory submission? For example, if the "Storm water drainage wells" type was selected, the app would reference a template specifically made for Storm water drainage wells. Similarly, if the "Subsurface environmental remediation wells" type was selected, the app would reference a template specifically made for SER wells and so forth.

**Comment by rsparker-utah** [comment]
@nathankota Sounds good, thanks Nathan. I'll work on getting each of the separate templates finalized.

**Comment by nathankota** [comment]
@rsparker-utah how are the templates coming along?

**Comment by rsparker-utah** [comment]
@nathankota I have draft copies in Google Docs for the following ABR letter templates:

- [General](https://docs.google.com/document/d/1W4Sm_-vEFRhq2Z_-uE2mw_gtmlK6-TaZw1SCB4PrxQ4/edit?usp=sharing)
- [Storm Water Drainage Wells](https://docs.google.com/document/d/1PH6eNWjaJ0YTirWOC56P1yQftyDxtresdUCSxjVWTF8/edit?usp=sharing)
- [Subsurface Environmental Remediation Wells](https://docs.google.com/document/d/1-jptVL4pIhDmcWN26Z4TdusHNR_tVS5ntjIz9qoFHLo/edit?usp=sharing)
- [UIC-Regulated Large Underground Wastewater Disposal Systems (LUWDS)](https://docs.google.com/document/d/11gcwbUdaEWWpzI_n7UfZcKrVzUtHfJEU3u3xe5a_nO4/edit?usp=sharing)
- [Veterinary, Kennel, Pet Grooming Wastewater Disposal Systems](https://docs.google.com/document/d/1Sw6S3tl0OO5N2WMks0UJAJgof1Iz6DfFzs-ohLHYebA/edit?usp=sharing) 

I followed [Brianna's original template document](https://docs.google.com/document/d/16x-y-FnVOzD_jKCPnInoUsQnWK8m9exb4kjlmHK8OaA/edit?usp=sharing) from issue #167 as well as past ABR letters when creating these individual drafts. I made some slight adjustments to verbiage to account for the UIC web application. While creating these templates I essentially separated the ABR letter into three sections:

- Intro
- Body
- Closeout

The “Intro” and “Closeout” sections remain fairly constant across all of the well subclass types. The “Body” section is where each letter varies according to the well subclass (here is an [outline](https://docs.google.com/document/d/1tVdc9q6-UnYVT8Q6YtTd6oFuAnm8VfSBs0ntmFb3s5M/edit?usp=sharing) of this structure for reference). 

I've asked Mark and Porter to review these templates and provide any feedback they may have regarding wording, layout, and content within each template to make sure they meet the needs/requirements of our UIC program.

**Comment by steveoh** [comment]
Where do these letters fit into the process? The last issue mentioned they showed up after clicking approve. But this issue doesn't mention when to show this text and what to do with it once it's shown. Is it to be printed and possibly mailed or electronically sent somewhere?

**Comment by nathankota** [comment]
> Where do these letters fit into the process? The last issue mentioned they showed up after clicking approve. But this issue doesn't mention when to show this text and what to do with it once it's shown. Is it to be printed and possibly mailed or electronically sent somewhere? #168 seems to have the information
> 

Yes, #168 is the one. Working to confirm those steps with UIC admins.

**Comment by steveoh** [comment]
I created a draft of the general abr letter. To access it click approve on a general well inventory.

**Comment by nathankota** [comment]
> I created a draft of the general abr letter. To access it click approve on a general well inventory.

This is looking great! I'm going to close this and start some new issues that are specific to each ABR type.
