### ISSUE TITLE
Update NAICS data files with 2022 data

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#228]
So the NAICS selector features has the latest data.

Update:
https://github.com/uic-utah/uic-inventory/tree/main/src/api/Features/Naics/data

With:

[2-6 digit_2022_Codes.xlsx](https://github.com/uic-utah/uic-inventory/files/11276179/2-6.digit_2022_Codes.xlsx)

[2022_NAICS_Index_File.xlsx](https://github.com/uic-utah/uic-inventory/files/11276182/2022_NAICS_Index_File.xlsx)

Also found [here](https://www.census.gov/naics/?48967).

**Comment by nathankota** [comment]
Looks like there are an additional 316 records in the 2022 data. I did a spot check of the tool for some of the new data, and it looks good. Before this issues is closed, do we want/need a task to remove the [2017 files](https://github.com/uic-utah/uic-inventory/tree/main/src/api/Features/Naics/data)?

**Comment by steveoh** [comment]
We're operating on the [dev branch](https://github.com/uic-utah/uic-inventory/tree/dev/src/api/Features/Naics/data) and it's taken care of.
