### ISSUE TITLE
App connect to DDW AWS database

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#229]
DDW database was moved to AWS after the firewall was initiated for the UIC app to communicate with DDW via the vpc interconnect to an on prem database ([RITM0196543](https://utah.service-now.com/nav_to.do?uri=%2Fsc_req_item.do%3Fsys_id%3Dccfa7e8687ae495002637489cebb35e2%26sysparm_stack%3D%26sysparm_view%3D)). 

We need to establish a new connection between the UIC app and the DDW database in AWS.

**Comment by steveoh** [comment]
I think we can keep that private. i'd say go ahead and start the firewall process for what we have now and we can modify it later as things evolve.

**Comment by steveoh** [comment]
Yes

**Comment by nathankota** [comment]
[REQ0167899](https://utah.service-now.com/sc_request.do?sys_id=fa71bd8a475225d4184a874c346d43e2&sysparm_record_target=sc_request&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog), [RITM0237929](https://utah.service-now.com/sc_req_item.do?sys_id=7271bd8a475225d4184a874c346d43e3&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog)

**Comment by nathankota** [comment]
Firewall was approved by DEQ IT Director. Followed-up just now with DGO DevOps team about the pending technical approval.

**Comment by nathankota** [comment]
@steveoh the firewall rule is complete and ready for testing.

**Comment by nathankota** [comment]
- [ ] [REQ0167899](https://utah.service-now.com/sc_request.do?sys_id=fa71bd8a475225d4184a874c346d43e2&sysparm_record_target=sc_request&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog), [RITM0237929](https://utah.service-now.com/sc_req_item.do?sys_id=7271bd8a475225d4184a874c346d43e3&sysparm_record_target=sc_req_item&sysparm_catalog=e0d08b13c3330100c8b837659bba8fb4&sysparm_catalog_view=catalog_Service_Catalog): For connection of cloud app environment to DDW database. Ready for acceptance testing, but after the request below is completed and tested
- [ ] [REQ0168198](https://utah.service-now.com/nav_to.do?uri=sc_request.do%3Fsys_id=ede473fb475a6d10184a874c346d43ce%26sysparm_stack=sc_request_list.do%3Fsysparm_query=active=true), [RITM0238301](https://utah.service-now.com/sc_req_item.do?sys_id=65e473fb475a6d10184a874c346d43cf): For UGRC VPN group to connect to DDW database for local testing and troubleshooting.

**Comment by nathankota** [comment]
validated via inventory [156](https://uic-inventory.dev.utah.gov/review/site/60/inventory/156). I'll keep in eye on the other firewall request for the ugrc vpn group to connect to DDW
