### ISSUE TITLE
Transfer app data to UIC prod db

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#230]
How to build a process to do this, considering:
- the app db has relationships, but not the same schema as UIC prod
- the existing versions and reconcile/post convention and process
- complexities of transferring projects vs. changes/updates vs. deletions
    - unique IDs
    - dif checks
- the use of triggers
- insert and update via versioned view
- and so on...

**Comment by rsparker-utah** [comment]
@nathankota I've been brainstorming an initial idea after reviewing the ESRI [versioned view article](https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/overview-edit-versioned-data-with-sql.htm). My thought is to create a new database connection and version (e.g., UICWEBAPP) in the UIC Geodatabase that the web app could write to. My thinking is that this would provide an independent version that the web app could write to that could then be reconcile and posted along with the other user versions on a weekly basis. 

The one unknown with this approach that I am still looking into is if there is a way for other users to view the data in the UICWEBAPP version without preventing the web app from writing to the version (e.g., geodatabase locks). The idea here would be to allow users to view the latest data written to the UIC Geodatabase by the web app without causing locks (and preventing further editing by the web app) or having to go through the entire reconcile post process every time the web app writes new data to the geodatabase.

**Comment by steveoh** [comment]
I don't believe versioned views are affected by locking but I could be wrong. 

One clarifying point... The web app should not connect directly to the UIC database. We are moving away from directly connecting to external databases and prefer to interact with API's. This allows the app to communicate with the API in a consistent fashion. The UIC database can grow and change independent of the app without causing issue to the app.

**Comment by nathankota** [comment]
@rsparker-utah Good ideas here, thank you. There's a dev version of the UIC database that you can test the steps in the `Editing options` > `Edit a named version` section of the article, yes?

**Comment by nathankota** [comment]
closing, in favor of more specific issues/tasks for data transfer and synchronization as they arise
