### ISSUE TITLE
General ABR letter - Well subclass and EPA code

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#235]
Although initially chosen by the inventory submitter as "General", the well subclass (and eventually an associated EPA code) displayed on the ABR letter is ultimately populated by the reviewer's Inventory Class selection on the review page. The rule still applies that if the reviewer chooses one of the other four primary subclass types, that specific ABR letters will be generated. 

The [EPA Well Code TO UICWellSubclass sheet](https://docs.google.com/spreadsheets/d/1FjCFibos_Q9OlQJZtc8owUHGfbtrSBXZOp7-aMHHMXQ/edit#gid=0) shows the proper EPA codes to use.

**Comment by steveoh** [comment]
If the app needs static data like codes, we will add them directly to the app. That is the convention we have been while developing this app.

The UIC database and this app are completely separate on purpose and no link between them has been used or created.

**Comment by nathankota** [comment]
I see that EPA codes are appearing now in the General ABR letter based on the four digit numeric values from the domain table. These codes will change once @rsparker-utah validates the existing list of subclass types on the review page of the app, and associated [EPA codes](https://docs.google.com/spreadsheets/d/1d59MZYqrfqzPSWIooQGXZUDRaPs1Lq1UiZ1rQpV2nAw/edit?hl=en#gid=0).

**Comment by rsparker-utah** [comment]
Porter and I went through the [EPA codes](https://docs.google.com/spreadsheets/d/1d59MZYqrfqzPSWIooQGXZUDRaPs1Lq1UiZ1rQpV2nAw/edit?usp=sharing) list and compared them to our ["UICWellSubClassDomain" gdb domain](https://docs.google.com/spreadsheets/d/1EzFA0h8zyt0IVZccfiUBvE4WozM5Sui3zv_UCqsAumM/edit?usp=sharing). The exact wording of the well subclass descriptions differs slightly between EPA's code list and our "UICWellSubClassDomain" UIC gdb domain, so we put together a [crosswalk spreadsheet](https://docs.google.com/spreadsheets/d/1FjCFibos_Q9OlQJZtc8owUHGfbtrSBXZOp7-aMHHMXQ/edit?usp=sharing) that can be used to match the EPA well codes/descriptions to our existing "UICWellSubClassDomain" gdb domain codes/descriptions. The codes in the "Corresponding EPA Well Code" column (column C) of this crosswalk spreadsheet can be referenced to populate the "EPAWellCode" section of the ABR template.

**Comment by nathankota** [comment]
initial comment updated according to the most recent information

**Comment by steveoh** [comment]
using the new uic values from the sheet the inventory creation screen will change from 


![Image](https://user-images.githubusercontent.com/325813/234720268-7b59eb26-82c2-4ec3-a227-6a9ebc68e041.png)

to


![Image](https://user-images.githubusercontent.com/325813/234721919-a3f37f1a-6025-4ff7-b3bc-617b3d8b9af4.png)

Is this ok?

**Comment by nathankota** [comment]
This works well. When a subclass type is modified on the Inventory Review page the proper EPA code displays with the chosen/saved subclass type in the ABR letter and on the Site/Inventory page. I noticed that, if SER is chosen on the Inventory Review page, it is allowable even though the extra SER information (agency contact, remediation type and project id) was not included in the original submission. Although the reviewer could go back and add an agency contact, they would not be able to edit the submitted well point to include the additional SER data. They _could_, however, delete a submitted point and add a new one in the same place with the required information. This is more of something for the reviewers to be aware of.

I am ready to validate this as-is, without any consideration about a subclass modification to SER by reviewers, once I get the okay from UIC admins @rsparker-utah.

**Comment by rsparker-utah** [comment]
@nathankota Thanks Nathan, this sounds fine as-is.
