### ISSUE TITLE
ABR letters - remove or replace FacilityID

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#236]
All of the ABR letter templates include FacilityID in two places. The problem is that FacilityID is not generated until a new site is entered into the UIC database. We do not yet have a process defined to transmit app data to the UIC database and, therefore, generate FacilityID and enter it into the ABRs. 

### Decision:
- At first we will either remove the FacilityID from the ABR letters, or replace it with another attribute (@rsparker-utah will help with this decision).
- Then sort out the post-approval editing rules and requirements.
- And define the data transfer requirements, understanding that an ideal situation is to initiate data transfer _during_ approval, so the FacilityID can be generated in the UIC database and immediately fetched for the ABR letter.

**Comment by rsparker-utah** [comment]
See also issue #259

**Comment by nathankota** [comment]
closing in favor of #259
