### ISSUE TITLE
Change Cancel to Back on ABR letter page

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#239]
- On the `/authorization` page where the ABR letter is displayed
- Change `Cancel` button to `Back` 
- When `Back` is clicked, it goes back to Inventory Review page

**Comment by steveoh** [comment]
Since cancel doesn't perform an action, should the button be labeled `Back`

**Comment by nathankota** [comment]
I thought about that too...yes, a `Back` button seems more appropriate here.

**Comment by steveoh** [comment]
Do you want to update the issue and title since no action is being taken other than navigation.

**Comment by nathankota** [comment]
> Do you want to update the issue and title since no action is being taken other than navigation.

Thank you for the reminder. Done.

**Comment by nathankota** [comment]
Back buh-ehn looks good, but clicking it does opens a new browser tab...

![image](https://user-images.githubusercontent.com/15659642/236062429-f14b5c72-e980-4ced-87f4-2c73c8d1cbe7.png)

**Comment by nathankota** [comment]
validated
