### ISSUE TITLE
Enforce post-submittal well addition completeness

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#240]
## Problem statement
If new well point(s) are added by UIC admins when inventory status is Submitted, or by regulated community users when inventory status is Approved, and well details are NOT completed for the additional well(s), the inventory status changes to Draft. A solution is needed to enforce users to enter both location _and_ construction details for new well entries in order to maintain the inventory status.

## Possible Solutions
1. For each new added well point immediately advance to the well details page.
  This might be cumbersome if more than one well point needs to be added, especially if the multiple new wells have the same construction details.
2. For each added well point, show a message that they must click next and enter well details, but let them stay on the well entry page. 
3. For each added well show a dialog/message AND when they click ok or something in the dialog, immediately advance to the well details page. 
4. Once a new point is added, open a dialog on the page that replicates the construction details page and if they don't complete it the well is not saved.

**Caveat:** For solutions 1-3 the possibility exists that they will still skip the construction details, so we would need to define rules about when and how to determine that the new wells are missing construction details and are therefore not saved, so the inventory status does not stay as reverted to Draft.

**Comment by nathankota** [comment]
@rsparker-utah what are your thoughts about the rules here?

**Comment by nathankota** [comment]
@rsparker-utah

**Comment by rsparker-utah** [comment]
@nathankota Apologies for the delayed response. Assuming the level of effort is similar to implement each of these options, we are leading towards option 4: 

> 4. Once a new point is added, open a dialog on the page that replicates the construction details page and if they don't complete it the well is not saved.

**Comment by nathankota** [comment]
closing for now since we are not doing post-approval editing
