### ISSUE TITLE
Inventory Review: Add well name/construction to the well details sections

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#242]
So that it is more obvious which wells are associated with each description or uploaded file, add the well name/construction to the associated information in the Construction Details, Injectate Characterization, and Hydrogeologic Characterization (#241) sections of the Inventory Review page and the printable inventory report.

Add these names/construction types:
![image](https://user-images.githubusercontent.com/15659642/234604990-a55fd0ea-161e-481d-986c-66bb4d1dc572.png)

To their associated information:

![image](https://user-images.githubusercontent.com/15659642/234605237-96d44f0a-b48f-4737-a009-3cc2cdfd9c70.png)

**Comment by steveoh** [comment]
So add `Well Name` above the `Construction` label?

**Comment by nathankota** [comment]
> So add `Well Name` above the `Construction` label?

Yes, and above the `Injectate Characterization` label; as well as `Hydrogeologic Characterization` once #241 is addressed

**Comment by nathankota** [comment]
validated
