### ISSUE TITLE
Make action buttons more prominent

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#244]
- [x] Well Location page:
> when all required information is entered for the well and the "Add" button then becomes clickable, can it also change colors to something more obvious like green?  It goes from being greyed out (not clickable) to dark blue (and clickable).  It's hard to notice that and then know to click "Add" before hitting "Next".  
![image](https://user-images.githubusercontent.com/15659642/234701779-d224cb92-5049-43a5-bebe-3fb7ee79ebeb.png)

- [x] Well Details page:

> Also on this page, if the Update button could change colors to something more obvious once all the information is entered that would be helpful.
![image](https://user-images.githubusercontent.com/15659642/234702189-5cce1cfc-fe7e-4574-9c33-06fb1ba4e28b.png)

**Comment by steveoh** [comment]
I updated the whole thing with respect to buttons. The back button is muted, action buttons are indigo, tools are orange, and the progress buttons are the gray.

**Comment by nathankota** [comment]
excellent!

**Comment by rsparker-utah** [comment]
Looks great!
