### ISSUE TITLE
Allow multiple parcels to be selected to represent a site

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#246]
> On the Site Location page, allow for the selection of more than one parcel for a site. Currently, one would have to "draw site" to define more than one parcel. With some of the crazy parcel shapes it would be helpful to be able to select more than one parcel to create a site instead of having to draw it manually.

- click on parcels to select them
- click again to deselect

**Comment by nathankota** [comment]
@steveoh I'm interested to hear from you about whether this is a massive departure from how the app currently works, or what.

**Comment by nathankota** [comment]
This works great to click to select additional parcels. There also needs to be the ability to deselect a parcel. Please enable a click on a selected parcel to _deselect_ the parcel.

**Comment by steveoh** [comment]
I didn't add that since the original ask didn't have it.

**Comment by nathankota** [comment]
> I didn't add that since the original ask didn't have it.

I understand. Oversight on my part.
