### ISSUE TITLE
Inventory Review and Approval Workflow Story

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#247]
## The workflow we are currently using is as follows:
- Receive Inventory Application submission

     - Import into Edocs if not already in Edocs

- Mark reviews Inventory Application submission for completeness (e.g., owner contact information, well details, Well/site location, signed form)

- Mark confirms Inventory fee payment with finance staff (match inventory submission applicant info to fee record provided by finance staff)

- Mark initiates Adobe Sign workflow and sends Inventory Application to Porter 

- Porter reviews/approves Inventory Application, then approved application is returned to Mark

- Mark enters Inventory Application information into the UIC geodatabase (via his user specific version) in accordance with the [data entry workflow](https://docs.google.com/document/d/1d5q_TNONpjDRFjKDx8Mhx9vw3tTfRJDAi-JaG2AzFjs/edit?usp=share_link)

- Mark composes a ABR letter email based on inventory type (e.g., storm water drainage, SER, LUWDS, etc.)

  - Adds generated facility ID from UIC geodatabase to letter

  - Adds pertinent courtesy contacts (specific courtesy contacts depend on inventory type)

- Mark sends ABR email to inventory contacts and relevant courtesy contacts

- Mark prints the ABR letter to pdf format from Gmail

- Mark imports the pdf ABR letter into the appropriate folder in Documentum, adds the required Documentum metadata, and the ABR letter is auto-assigned a Edocs (i.e., Edocs) number by the system

- Mark then edits the ABR Letter document to include the previously assigned Edocs number

## Our proposed workflow post Inventory Review page is as follows:
- Review and approve information on Inventory Review Page

- Manually get Edocs number for approved inventory form

  - Insert Edocs number into Inventory Review Page

- Approved inventory information gets entered into UIC geodatabase (automated if possible (e.g. [version view](https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/overview-edit-versioned-data-with-sql.htm)), manual entry otherwise)

  - Retrieve generated Facility ID from geodatabase

  - Insert generated Facility ID into Inventory Review Page (can this field be added to the “Inventory Review” page?)

- Generate ABR letter within web app based on well subclass template (“Generate ABR” button?)

  - Add relevant courtesy recipients to the generated ABR letter based on well subclass (manually?)

- Review completed ABR letter

- Merge Inventory Review Form (IRF) and ABR Letter into a single completed pdf document which includes:

  - Approved IRF including any supplemental attachments (e.g., construction details, injectate details)

  - Completed ABR letter

- Send (email) completed pdf document to all inventory contacts and courtesy recipients 

- Download completed pdf document

- Import completed pdf document to Edocs

We made the following assumptions while putting this proposed workflow together:
1. File upload type for the construction and injectate details are limited to .pdf and this will allow for the merging/download of the inventory, ABR letter, and any existing attachments in a single compiled .pdf file.
2. A new editable "Facility ID" field (i.e., similar to the "Edocs" field) could be added to the "Inventory Review" page.
*NEW ASSUMPTION* (added by Nathan 5/24/2023)
3. Ability to add courtesy recipients (who are not Site contacts) during approval so they will receive the approval email.

**Comment by nathankota** [comment]
validated, until any changes are needed and can be added

**Comment by nathankota** [comment]
oops, I accidentally closed the wrong issue...reopening

**Comment by rsparker-utah** [comment]
@nathankota This looks good, thanks Nathan.

**Comment by nathankota** [comment]
this has been replaced by the [inventory review workflow doc](https://docs.google.com/document/d/14AGnU_Ou_T66C6VBhdcCpXg8bcIKkTtkBeOXjPY7ZYI), which will be used to define new issues/tasks
