### ISSUE TITLE
Inventory Review and ABR pdf mock-up

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#249]
The sixth bullet point of the proposed approval workflow (#247) is:
- _Merge Inventory Review Form (IRF) and ABR Letter into a single completed pdf document which includes:_

  - _Approved IRF including any supplemental attachments (e.g., construction details, injectate details)_

  - _Completed ABR letter_

@rsparker-utah please provide a mock-up of the expected layout for a pdf of the combined inventory report, attached docs, and ABR letter.

**Comment by rsparker-utah** [comment]
@nathankota I'm in the process of creating this mock-up.

**Comment by rsparker-utah** [comment]
@nathankota I've put together a [mock-up draft layout](https://drive.google.com/file/d/1ZUOxe6IHige4zv40s-E_o77q7S88LYIU/view?usp=sharing) for a pdf of the combined inventory report, attached docs, and ABR letter. I used [site ID 97](https://uic-inventory.dev.utah.gov/review/site/97/inventory/183) as the reference for this mock-up. This is purely a draft and I am open to suggestions.

**Comment by nathankota** [comment]
We spoke about some changes to the ABR letter and the layout of the Inventory Report, such as:
- remove courtesy contacts
- define page breaks for different sections
- specify how uploaded docs vs. text descriptions are displayed for well details

**Comment by rsparker-utah** [comment]
@nathankota I've been reviewing this with my colleagues. We're bouncing around some ideas and I'll add an updated mock-up draft once we make some final decisions.

**Comment by rsparker-utah** [comment]
@nathankota I've thrown together an [updated mock-up](https://docs.google.com/document/d/16-ri5ux1-8d--hUtMINO_oWBVt5z45CqjugJfoMwCT4/edit?usp=sharing). I left it in the Google Docs format for the time being to allow for commenting. I have added a few comments within the mock-up to provide some background behind some of the formatting choices. A few of the proposed formats within this updated mock-up (i.e., the formatting for uploaded docs vs. text descriptions and the Location Details page) were based on assumptions and may require adjustment and/or additional discussion. Any feedback/suggestions welcome.
