### ISSUE TITLE
Parcel select/deselect for existing site location

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#250]
TBD

**Comment by nathankota** [comment]
@rsparker-utah can you help me with this one? If we lock editing to public users after they submit an inventory then I don't think there's much of an issue. However, if there is a site with a Draft inventory and we are letting them continue to edit Site Location, some changes need to happen. Please check out a site that only has draft inventories, and examine the workflow for changing the site location, particularly using Select Parcels, and provide some input on how you want it to work. 
An example of a site with a draft inventory is [site 72](https://uic-inventory.dev.utah.gov/site/72/add-location).

**Comment by rsparker-utah** [comment]
@nathankota I think it makes sense to lock public users ability to edit a site after they submit an inventory. 

I went through the process of changing the site location using [site 72](https://uic-inventory.dev.utah.gov/site/72/add-location) as the example. This is the process I used to change the site location:

- I navigated to the "Site Location" page,
- I selected the "Select Parcels" tool to reset the site location (I also tried this with the "Draw Site" tool),
- I then experimented with selecting and deselecting parcels while the "Select Parcels" tool was active and then selected a new parcel,
- I then clicked "Next" to save the updated site location.

Based on the above, I found the current functionality to be intuitive. The only suggestion I can think of is that it may be helpful to add a bit of extra explanation text for the user to let them know they have the ability to click either the "Select Parcels" or "Draw Site" tools again to reset the site location. 

I did notice one possible bug while going through this process. I added a separate issue (#271) for this bug.

**Comment by nathankota** [comment]
Thanks for adding that new issue (#271) @rsparker-utah. I think this issue should be closed, in favor of #217. 

Let's punt on your suggestion about adding some additional explanation for now, because I _think_ the existing instructions on the page (below) might be sufficient. Once we get some usage of the app we can determine if it's an issue and deal with it then.
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/58ddb606-114a-4db9-8de3-4078df2077a3)
