### ISSUE TITLE
Other well status: show modified description in popup

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#251]
### Observed
- create new well where status = other
- enter text for description and set well location
- hover on "Other" text for popup of description
- click modify and enter new description, then save
- hover on "Other" text and the original description still appears
### Expected
- in final step above the modified and saved description should appear in the "Other" popup

**Comment by nathankota** [comment]
The description text for an existing well cannot be modified/edited.

**Comment by nathankota** [comment]
I get an error when attempting to update a description for an existing Other, and when modifying from one status to another does not save the new status.

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/802b8f05-0a13-47d9-ab74-e11eb6dd1abc)

**Comment by steveoh** [comment]
https://github.com/uic-utah/uic-inventory/issues/113#issuecomment-1535663197

**Comment by nathankota** [comment]
> You are validating that there is a popup with content in this issue right?
> 
> [#113 (comment)](https://github.com/uic-utah/uic-inventory/issues/113#issuecomment-1535663197)

popup validated via #248
