### ISSUE TITLE
Approved inventory notification - well status edits

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#254]
### Modify status
**Notification message:** _NK changed well status from ____ to ____ for inventory 110_ [date, time] 🔗 ✉️ 🗑️

### Modify Other status description
**Notification message:** _NK changed well status from Other to Other for inventory 110_ [date, time] 🔗 ✉️ 🗑️

**Comment by steveoh** [comment]
@nathankota this was completed as a part of #148.

**Comment by nathankota** [comment]
This looks like it kicks a notification when an inventory's status is Submitted and will, therefore, also notify once we have an Approved status flow completed, so I will close as validated.
