### ISSUE TITLE
well status optimistic update does not reset when canceled

### ISSUE THREAD

**Issue by steveoh** [uic-utah/uic-inventory#256]
- Select the "modify" icon under well operating status
- Select a new well operating status from the drop down list
- Click the "cancel" button

This does in fact cancel the selection, but leaves the last selected well operating status still visible in the UI which could be confusing for the user. Refreshing the page shows the correct operating status again. This bug/glitch is extremely minor (I would consider it low priority) and I can't it see it happening often, but thought I would mention it in case there is an easy adjustment. 
![Cancel_Button](https://github.com/uic-utah/uic-inventory/assets/49735267/622804ba-9513-40e4-99ad-0b48c41cc0f4)

_Originally posted by @rsparker-utah in https://github.com/uic-utah/uic-inventory/issues/113#issuecomment-1552023960_

**Comment by nathankota** [comment]
validated
