### ISSUE TITLE
Contact Last Names Not Displaying on Inventory Review Page

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#257]
Contact last names aren't displaying within the Site Contacts section on the Inventory Review page. 

For example, the [site contacts for site ID 97](https://uic-inventory.dev.utah.gov/site/97/add-contacts) are:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/e9286def-69dc-4523-b27d-4a874cef58f2)

When reviewing the Site Contacts section of the [Inventory Review Page](https://uic-inventory.dev.utah.gov/review/site/97/inventory/183) for this site, only the first names for each of the contacts is being displayed:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/e16fef34-2780-484c-bd81-5ce6d9a92a78)

This appears to be happening on each submitted inventory.

**Comment by nathankota** [comment]
validated
