### ISSUE TITLE
Site Location

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#26]
As a regulated community user I must define the location of a site with a point and a boundary.

### Point

- Search for existing addresses and locations using UGRC's [Sherlock](https://github.com/agrc-widgets/sherlock) and [Dartboard](https://github.com/agrc-widgets/dart-board) widgets
- If address is found, allow user to select it
- If no address found, allow user to digitize a point

### Boundary

- If parcel exists where point was saved, highlight it and allow user to select
- If no parcel, or parcel does not accurately represent the site, allow user to digitize site boundary
- **NOTE:** the boundary **_must_** contain the point. If not, show error message to alter boundary or point.

**Comment by nathankota** [comment]
[Dartboard](https://github.com/agrc-widgets/dart-board) implemented, but not yet [Sherlock](https://github.com/agrc-widgets/sherlock) or, if it cannot be included, then the ability to digitize a point location when an address cannot be found or does not exist for a Site.

**Comment by steveoh** [comment]
All of that works without sherlock at the moment. I wasn't convinced sherlock was necessary.

**Comment by nathankota** [comment]
Okay, I am not seeing the point digitizing feature, but maybe it hasn't been deployed so I'll hold my horses.

**Comment by steveoh** [comment]
It is accessible when your address is not found currently

**Comment by nathankota** [comment]
Yes, that would be great. Brianna has said that sometimes there are not yet defined addresses if they are new developments that have not been addressed, or other scenarios where people have formerly provided general descriptions.

**Comment by nathankota** [comment]
This workflow looks good. Other issues will be created if necessary to hone certain aspects of it.
