### ISSUE TITLE
Inventory Review Page - Remediation type and Remediation project id Not Showing For SER Wells

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#262]
The values for "Remediation type" and "Remediation project id" (entered on the "Well Location" page and unique for SER wells) are not showing on the Inventory Review Page for SER wells (See [site 84, inventory 152](https://uic-inventory.dev.utah.gov/review/site/84/inventory/152) for an example). Could these fields be included on the Inventory Review page for SER wells?

**Comment by nathankota** [comment]
@rsparker-utah respectfully requesting your testing of this issue

**Comment by rsparker-utah** [comment]
Tested and validated for both an existing site/inventory [(site 84, inventory 152](https://uic-inventory.dev.utah.gov/review/site/84/inventory/152)) and a newly created site/inventory ([site 110, inventory 202](https://uic-inventory.dev.utah.gov/review/site/110/inventory/202))
