### ISSUE TITLE
Your sites and inventory page - "Toggle SortBy" functionality and "ID" Column

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#263]
Are the numbers in the "ID" column on the main app page established chronologically based on when a site was created? If so, is it possible to add the "Toggle SortBy" functionality that is present on the "NAME" and "TYPE" columns to the "ID" Column to allow for chronological sorting?
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/8ef25fbf-9d94-40df-b993-5bd24e49395d)

**Comment by steveoh** [comment]
this was added during a table refactor. please validate.

**Comment by rsparker-utah** [comment]
Works great, thanks you!
