### ISSUE TITLE
Document Size Consideration for Completed Inventory Packet

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#265]
Currently, the [completed Inventory Packet](https://github.com/uic-utah/uic-inventory/issues/249) (i.e., the combined ABR letter and inventory review form) is planned to be an attachment to an automated approval email after inventory approval. We will need to consider options regarding file size limitation given that Gmail has an attachment size limit of 25 MB. 

One option would be to limit the file size of uploads for the Construction Details and Injectate Characterization sections on the Well Details Page in the app to help prevent the completed inventory packet document from exceeding the 25 MB attachment limit of Gmail. Specific file size limitations for the Construction Details and Injectate Characterization sections will be dependent on the finalization of the [completed inventory packet](https://docs.google.com/document/d/16-ri5ux1-8d--hUtMINO_oWBVt5z45CqjugJfoMwCT4/edit) and [ABR templates](https://drive.google.com/drive/folders/1z_v1Ors9vV0iU-zC2a0wtbug6Qk2M55Y?usp=drive_link).

**Comment by nathankota** [comment]
@rsparker-utah will define file upload size threshold for [construction and injectate details](https://uic-inventory.dev.utah.gov/site/71/inventory/155/add-well-details).

**Comment by rsparker-utah** [comment]
Closed in favor of #268

**Comment by nathankota** [comment]
A newly-defined approval workflow eliminates the need for upload file size restrictions
