### ISSUE TITLE
File Upload Type and Size Limitation for Well Construction Details and Injectate Characterization

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#268]
On the "Add Well Details" page, for the Construction Details and Injectate Characterization sections, please:

- limit the file upload type of uploads to .pdf, 
- limit the file upload size for Construction Details to 10 MB,
- limit the file upload size for Injectate Characterization to 10 MB.
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/c82b2b6a-d936-4cde-86e2-f7d34e6e5196)

The goal behind this is to help prevent the completed inventory packet document from exceeding 25 MB.

**Comment by steveoh** [comment]
You're shooting for 25mb packet by limiting 2 documents from one well? You can create 20 wells right?

**Comment by rsparker-utah** [comment]
Hmmm good point. Do we have other options for limiting the size of the final packet to 25 MB? This restriction is necessary since we will be manually emailing (via gmail) the completed packet as an attachment to the submitter.

**Comment by nathankota** [comment]
There is the option to zip files to reduce the attachment size in emails, but that could be an unreliable solution. Ryan, we talked about limiting the size of _**all**_ uploaded files across each of the data "fields" (for lack of a better term) to 10MB, if that is possible @steveoh. In other words, all the uploaded files added together for construction details _or_ injectate characterization, respectively, cannot exceed 10MB.

**Comment by steveoh** [comment]
This size restrictions will likely create a poor user experience for people trying to enter data. 

Can we provide access to the packet through the website independent of it's download size via a link or something in the email and remove the size constraint considerations all together?

**Comment by nathankota** [comment]
> Can we provide access to the packet through the website independent of it's download size via a link in the email and remove the size constraint considerations all together?

I like this recommendation. 

@rsparker-utah , what about:
- Provide a link to the [Inventory Review page](https://uic-inventory.dev.utah.gov/review/site/71/inventory/155) in the ABR letter, **_and_** you could double-up and also provide the link in the email.
- The `Print` button on the Inventory Review page prints/downloads the report with all uploaded docs/attachments.
- The `Approve` button only generates the ABR letter, which would be the only document you include in the email, unless the inventory report is small enough and you feel like downloading it (using the `Print` button) and attaching to the email.
  - This would be a change from the Approve workflow from generating ABR+inventory report, to only generating ABR.
  - We already talked about having some indicators to show when an inventory is approved, yet `Approve` could be clicked  again and again even after approval, and would generate new ABR letters. One important thing to consider is the [date included on the ABR letter](https://docs.google.com/document/d/1W4Sm_-vEFRhq2Z_-uE2mw_gtmlK6-TaZw1SCB4PrxQ4/edit), which would change each time `Approve` is clicked, unless we store the date of the first time it was clicked (`UICAuthorization.StartDate`). Another option is to only allow `Approve` to generate an ABR once, but that could be problematic if you lose the original document.

Thoughts?

**Comment by rsparker-utah** [comment]
@nathankota I like this approach that you've outlined. I'm all for it.

**Comment by nathankota** [comment]
closed in favor of #269, and @rsparker-utah will update the [post-approval workflow doc](https://docs.google.com/document/d/14AGnU_Ou_T66C6VBhdcCpXg8bcIKkTtkBeOXjPY7ZYI/edit) based on comments in this issue
