### ISSUE TITLE
Admin Editing Rules

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#272]
## Like public users...
- To add a site a user's profile must be completed
- To add an inventory, a site must be completed
- To submit an inventory, all required inventory data and pages must be completed
- Site can be edited and deleted if there are no submitted inventories
- Inventories can be edited and deleted when they are Draft

## Unique to Admins
- Site can be edited or deleted when inventories are Submitted and beyond. Deleting will delete all associated inventories.
- Inventories can be edited or deleted when their status is Submitted and beyond.

**Comment by rsparker-utah** [comment]
@nathankota This looks good, I don't see anything that needs to be changed.

**Comment by steveoh** [comment]
please validate these rules in the app

**Comment by nathankota** [comment]
The following rule is the only I cannot validate. Not able to edit or delete inventories with status Submitted and beyond.

> Inventories can be edited or deleted when their status is Submitted and beyond, without changes to the status. All required inventory data must be completed to advance/save the page.

**Comment by steveoh** [comment]
If I understand this correctly, that specific rule statement isn't working. 

I pushed a change to allow inventories to be edited or deleted when their status is submitted and beyond.

> without changes to the status

This doesn't make sense for deleting inventories.

It's not quite true for editing either since the database calculates the status based on the data available. If an admin deletes all of an authorized inventories wells or contacts, the status will revert to draft until the conditions are met to revert back to  authorized or whatever the prior status was.

> All required inventory data must be completed to advance/save the page

This doesn't make a lot of sense to me since admins are asking to override the rules and edit or delete anything anytime.

**Comment by nathankota** [comment]
> If I understand this correctly, that specific rule statement isn't working.

Correct - that specific rule statement.

----
> I pushed a change to allow inventories to be edited or deleted when their status is submitted and beyond.

I attempted to delete the top two inventories in the image below, with the following result:

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/baa42f11-4eb1-48d1-acc0-49efca11d48d)

----

> > without changes to the status
> 
> This doesn't make sense for deleting inventories.

Agreed, status changes wouldn't apply to deleted inventories. The statement was mainly meant for editing, and I see your comment below... 

----
> 
> It's not quite true for editing either since the database calculates the status based on the data available. If an admin deletes all of an authorized inventories wells or contacts, the status will revert to draft until the conditions are met to revert back to authorized or whatever the prior status was.

Thank you for the clarification there.  I will remove (or strike through) the part of the rule statement about the status not changing during editing.

----

> > All required inventory data must be completed to advance/save the page
> 
> This doesn't make a lot of sense to me since admins are asking to override the rules and edit or delete anything anytime.

I understand now that this doesn't apply, given the requested editing authority for admins. I will remove it also.

**Comment by nathankota** [comment]
> > I pushed a change to allow inventories to be edited or deleted when their status is submitted and beyond.
> 
> I attempted to delete the top two inventories in the image below, with the following result:
> 
> ![image](https://private-user-images.githubusercontent.com/15659642/328534598-baa42f11-4eb1-48d1-acc0-49efca11d48d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODg4MjksIm5iZiI6MTcxNTA4ODUyOSwicGF0aCI6Ii8xNTY1OTY0Mi8zMjg1MzQ1OTgtYmFhNDJmMTEtNGViMS00OGQxLWFjYzAtNDllZmNhMTFkNDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMjg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1OWNkNjBkZjg0MDkyMTFiNjU5MDBkYmE4YTJmZTQ4ZWFlNThmOTEyZGJkZjAxZjcyMzBiYWNiYWU1ZDkyYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqoVg3GL85q_O4TKCACJ7JTyZ1SR084vHCrf06xyen4)

This only seems to be an issue for the site and inventories I created. I am able to edit and delete sites and inventories that other users created.

**Comment by rsparker-utah** [comment]
I was able to test the admin rules and all of the rules were working as expected during my testing except:

>Site can be edited or deleted when inventories are Submitted and beyond. Deleting will delete all associated inventories.

This might just be a bug, but I was able to edit the site information using my admin account for some sites with submitted (or beyond) inventories (e.g., site 141), but not for others (e.g., 125 and 134). For example, I was able to edit the site details, location, and well details for site 141; however, I received error messages when trying to edit any of the site information associated with sites 125 and 134:
Site 125:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/62a83830-09e9-4002-8bd3-4ee7a1d3469b)
Site 134:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/a90a32a9-7335-45b9-85e6-187d1371bd90)

**Comment by steveoh** [comment]
are you the owner of the ones you can or can't edit?

**Comment by rsparker-utah** [comment]
For site 141 that I was able to edit with my admin account, my admin account was not the owner (my public "AWQMS AWQMS" account is the owner of 141).

For sites 125 and 134 that I was unable to edit, my admin account was the owner.

**Comment by steveoh** [comment]
The site is deploying now. Let's try to validate this again.

**Comment by rsparker-utah** [comment]
I completed another round of testing today (5/21/2024) for the Admin editing rules. Based on my testing, the rules are working as expected.

I tried the following during this round of testing:

### Like public users...

- To add a site a user's profile must be completed – **Validated**.
- To add an inventory, a site must be completed – **Validated**. I tested this by creating a site using my admin user account. I then tried creating inventories on the site when it was missing site contacts and/or the site location. In both of these scenarios, I was prevented from creating an inventory and directed to the incomplete site notification page. After adding the required missing site information, I was able to successfully create an inventory for the site. 
- To submit an inventory, all required inventory data and pages must be completed – **Validated**. I tested this by creating a site using my admin user account. After completing the required site information, I created several inventories with varying missing information (e.g., no specified location, no well details, no signature, etc.). I then tried submitting each of these incomplete inventories. For each of these incomplete inventory examples, I was prevented from submitting the inventory and directed to the incomplete inventory notification page. After adding the required missing inventory information, I was able to successfully submit the inventory. 
- Site can be edited and deleted if there are no submitted inventories – **Validated**. I tested this by creating a few sites using both my admin and public user accounts. I then tested editing and deleting these sites.  In each of my tests I was successfully able edit and/or delete the site. 
- Inventories can be edited and deleted when they are Draft – **Validated**. I tested this by creating a site using both my admin and public user accounts. After completing the required site information, I created several draft inventories I then tested editing and deleting these inventories using my admin account.  In each of my tests I was successfully able edit and/or delete a draft inventory. 

### Unique to Admins

- Site can be edited or deleted when inventories are Submitted and beyond. Deleting will delete all associated inventories. – **Validated**. I tested this by creating a few more sites using both my admin and public user accounts. I then created inventories for these sites at each of the different inventory statuses (e.g., Draft, Submitted, Under Review, Approved, Authorized, Completed). I then tested editing and deleting these sites using my admin account and was able to do so as expected.  
- Inventories can be edited or deleted when their status is Submitted and beyond. – **Validated**. I tested this by using the sites and inventories mentioned above. I then tested editing and deleting these inventories using my admin account and was able to do so as expected.

**Comment by steveoh** [comment]
sweet. shall we close this?

**Comment by rsparker-utah** [comment]
That would be great thanks!
