### ISSUE TITLE
Inventory Report layout

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#273]
**Using [the mockup document](https://docs.google.com/document/d/16-ri5ux1-8d--hUtMINO_oWBVt5z45CqjugJfoMwCT4/) as a guide (page 2 of the doc, onward).** 
(**Side note:** The PLSS app's monument record sheet was the inspiration for the report layout and design.)

### First Page(s)
- Title (see mockup doc)
- Site details (name, location, land ownership, naics, edocs, site ID
- Inventory details (inventory class, order number, signed by, signed on (date))
- Site contacts: separate table for each contact (name, org, type, email, phone, address)
  - multiple site contacts may cause this section to go beyond a single page

### New page
- Title: Location Details
- Map showing the site, wells, SWPZ and ARDA (if applicable to the inventory)
  - Label wells with their name/construction
  - Show source water protection zone layer as 50% transparent, and label with [SYSNAME](https://utahdeq.maps.arcgis.com/home/item.html?id=88293a87e2954112979e420222ffe3d9#data) 
  - Show aquifer recharge discharge areas as 50% transparent, different color than SWPZ, and label with [ZONE](https://opendata.gis.utah.gov/datasets/utah::utah-aquifer-recharge-discharge-areas/explore?showTable=true)
 
### New page
- Well information section table including a record for each well (count, construction, operating status, groundwater indicators (GWZ, ARDA)
- Water system information section (water system name, contact name, contact email)

### New page
- Title: Well Construction Details
- One section per well 
  - Show well name and Construction details text in each section
  - If document was uploaded, include text “See Appendix”
    - Append the construction details document at end of report
    - If multiple wells have the same uploaded document, only append the document once

### New page
- Title: Well Injectate Characterization
- One section per well 
  - Show well name and injectate characterization text in each section
  - If document was uploaded, include text “See Appendix”
    - Append the injectate characterization document at end of report
    - If multiple wells have the same uploaded document, only append the document once

### New page
- Title: Well Hydrogeologic Characterization
- One section per well
- Show well name and hydrogeologic characterization text in each section (no doc uploads allowed for this section)

### Last page(s)
- Title for each appended doc section, and the documents appended within the subsequent pages
  - Appendix 1: Well Construction Details
  - Appendix 2: Well Injectate Characterization

**Comment by steveoh** [comment]
are we running a footer like plss's
 
<img width="636" alt="image" src="https://github.com/uic-utah/uic-inventory/assets/325813/b53ee394-10d2-4df7-a527-0771ce6727f7">

**Comment by steveoh** [comment]
Here's the start. Any changes required for these?

<img width="642" alt="image" src="https://github.com/uic-utah/uic-inventory/assets/325813/e11ba604-18fe-4504-9464-e792e5dacd51">

**Comment by nathankota** [comment]
Looking great so far! @rsparker-utah, please review the draft above and comment on any needed changes so far.

**Comment by steveoh** [comment]
Here's a full sample. Please comment on it's format

[uic-report-sample.pdf](https://github.com/uic-utah/uic-inventory/files/13445503/uic-report-sample.pdf)

**Comment by nathankota** [comment]
DWQ team is currently reviewing and we expect feedback shortly.

**Comment by steveoh** [comment]
This is the most recent iteration.
[uic-form-sample.pdf](https://github.com/uic-utah/uic-inventory/files/13517553/uic-form-sample.pdf)

**Comment by steveoh** [comment]
Yes the email can be added. It's in there now and the spelling mistake is also corrected.

Provided it's ok to add the footer... who decides if it's ok?

**Comment by rsparker-utah** [comment]
Ok, gotcha, that sounds good. Our review group seemed to like the plss verbiage, but I better run it by Cate first. Let's hold of on that piece for time being. I'll provide an update after I chat with Cate.

**Comment by rsparker-utah** [comment]
I ran the disclaimer by our Data Management Specialist and have an update regarding the disclaimer. Could we add a sentence at the end of the existing disclaimer so it reads:

The State of Utah makes no guarantees, representations, or warranties of any kind, expressed or implied, as to the content, accuracy, timeliness, or completeness of any of the data. Unless otherwise noted all images are oriented North and are not to scale. The data is provided on an “as is, where is” basis. The State assumes no obligation or liability for its use by any persons. Identified inaccuracies can be reported to uic-inventory@utah.gov.

**Comment by steveoh** [comment]
I've pushed the work I have done so far to dev. Please test it and see what you think. The appendix files are not currently being fetched and attached. Otherwise I think we have everything in the report that was in the mockup. Make sure your browser allows a popup.

**Comment by nathankota** [comment]
As far as report layout, it looks correct/accurate/great to me. @rsparker-utah we now defer to you for final validation.

**Comment by steveoh** [comment]
the well detail pdf's are now appended to the report. I deleted all of the cloud storage to remove any non pdf files. When you test you will need to update the well details for the inventory you are testing to add new files.

**Comment by steveoh** [comment]
construction is fixed

![image](https://github.com/uic-utah/uic-inventory/assets/325813/f021f7ba-8b8e-4180-baa6-363f87adf640)

We should track any GWZ issues in a new issue

**Comment by steveoh** [comment]
Drinking water changed their service url. I've got that fixed now also.

**Comment by nathankota** [comment]
@rsparker-utah please give this another try

**Comment by rsparker-utah** [comment]
I did a new round of testing on a new site (i.e., https://uic-inventory.dev.utah.gov/review/site/119/inventory/213), submitted an inventory, and downloaded the Inventory Report. I didn't come across any issues and I think the report layout looks really good! Thanks Steve!
