### ISSUE TITLE
Approve inventory

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#275]
### UIC admin clicks `Approve` on Inventory Review page for a submitted inventory ([example](https://uic-inventory.dev.utah.gov/review/site/54/inventory/148))
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/3ddeffdc-b45d-4318-96b9-e2f0de1b9273)

- Confirmation notification appears on a new page or in a window within the browser

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

### `Cancel` 

- Click to go back to Inventory Review page without approving. Nothing changes.

### `Approve` 

- [x] Click to approve the inventory
- [x] Write authorization date to database
- [x] Update inventory status
- [x] Create notification for admin receiving notifications
- [x] Disable reject and approve button for all authorized inventories
- ~Email submitter?~ (this is achieved manually, where UIC admin will download and email the approval docs (ABR & inventory report) to the submitter)
- ~Data transfer to UIC database is initiated (process TBD)~

#### Success

- Loader animation in upper right corner of page 
   ✔️ Inventory approved and data sent! 
- Confirmation window/page closes and app goes back to Inventory Review page

#### Failure 

- Loader animation in upper right corner of page      
   ❌ Inventory approval and data transfer failed 😞 
- If possible, add details about the error within the confirmation window/page
  - Click `Close` or `Back` to close window or go back to Inventory Review page
- If not possible to add error details, the confirmation window/page closes and app goes back to Inventory Review page

**Comment by steveoh** [comment]
All that happens when the inventory is approved is the data is transferred? This seems incomplete to me. Or supplemented by another issue i haven't read yet.

**Comment by steveoh** [comment]
I edited this issue and i think we can close #276.

**Comment by nathankota** [comment]
> #### Success
> ...
> - Confirmation window/page closes and app goes back to Inventory Review page

After approval the app kicks to the default "Your sites and inventory" page.

The description in the initial issue comment is not as clear as it could be. Hopefully this is better. 
- Confirmation notification closes and app **_stays on_** Inventory Review page.

**Comment by steveoh** [comment]
I misread that, simple fix. Thanks!

**Comment by nathankota** [comment]
not sure if you were ready for testing, but it looks like it now stays on the inventory review page, yet the confirmation message remains

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/c561f66b-df63-4830-a111-116e6e5d8f5c)

**Comment by steveoh** [comment]
Thanks, new build is in the queue now

**Comment by nathankota** [comment]
- The app stays on the review page as expected. 
- The `Approve` and `Reject` buttons are not disabled until the page is refreshed, post-approval. 
- However, I realize I missed a piece of the requirement, which should be to show the Approved indicator at the top of the page, post-approval. This also occurs after the page is refreshed.

Seems like initiating an automatic page refresh after approval will resolve those remaining items.

**Comment by steveoh** [comment]
Your concerns have been fixed. Please validate.

**Comment by rsparker-utah** [comment]
I tested this using a newly created site and inventory (i.e., [site 120, inventory 218](https://uic-inventory.dev.utah.gov/review/site/120/inventory/218)). 

Here are the steps I took:

1. I used my public user account to create the new site and submit the inventory.
2. I then navigated to the Inventory Review page of the submitted inventory using my admin account and clicked the "Approve" button. 
3. The "Approve Submission Confirmation" dialogue box appeared as expected. I verified the "No" button exited out of the "Approve Submission Confirmation" dialogue box. 
4. I then clicked the "Approve" button again and clicked the "Yes" button in the "Approve Submission Confirmation" dialogue box to approve the inventory. Both the "Reject" and "Approve" buttons on the Inventory Review Page became immediately grayed out (and unable to be selected) as expected. Also, the "Approved" indicator containing approver information appeared at the top of the screen as expected (that "Approved" indicator is so cool!). 

This looks good to me and functioned as expected.

**Comment by nathankota** [comment]
@rsparker-utah 

Re: 
> Also, the "Approved" indicator containing approver information appeared at the top of the screen as expected (that "Approved" indicator is so cool!).

According to #279 the approver information will not appear, only the `Approved` indicator. Some approver information _**is**_ included on the ABR, _**but**_ it will change if another admin downloads the ABR & inventory report post-approval, since the approver info is not stored in the app database, and the downloaded documents are produced on the fly. 

I am ready to close this issue as validated, once you provide confirmation that the above scenario is understood.

**Comment by steveoh** [comment]
The approver is stored in the db with this migration https://github.com/uic-utah/uic-inventory/blob/dev/src/api/Migrations/20231220014456_AuthorizedBy.cs

I don't think the other stuff you mention is accurate either about it changing.

**Comment by nathankota** [comment]
> I don't think the other stuff you mention is accurate either about it changing.

> The approver is stored in the db with this migration https://github.com/uic-utah/uic-inventory/blob/dev/src/api/Migrations/20231220014456_AuthorizedBy.cs

Thank you, I was not aware.

> I don't think the other stuff you mention is accurate either about it changing.

Ryan said he approved https://uic-inventory.dev.utah.gov/review/site/120/inventory/218 yesterday. When I "Download" the approval docs:
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/21b75a1e-9d18-4c7e-8ef1-935b60012883)

**Comment by nathankota** [comment]
I believe the overall goal is achieved by
> ...the approver will always be the person who clicked authorize.

Doing some final validation with Ryan before closing.
