### ISSUE TITLE
capture AuthorizationActionDate when approved

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#276]
When an inventory is approved, the approval date should be 
- stored in the app database
- sent to the UIC database as the AuthorizationActionDate
- displayed on the Inventory Review page (#279)
- used to populate the date at the top of the ABR letter.

**Comment by steveoh** [comment]
this gives me a better picture as to what happens than #275

**Comment by steveoh** [comment]
This issue is basically only saying to capture the authorized date. The arb stuff is tracked somewhere else the review page is somewhere else, and the db sync is being tracked somewhere else.
