### ISSUE TITLE
Add status and approval details on review page

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#279]
<img width="341" alt="image" src="https://github.com/uic-utah/uic-inventory/assets/325813/86eaae16-8d89-4c6d-882a-f3cbcec06ffe">

#### After an inventory is approved,
- Add a green rectangle icon with "Inventory Approved" text under the Inventory Review title on the review page
  - The icon should scroll with the page, like the Flag with Issues button
- Under the Inventory Approved icon, add some approval details, which will also be included in the ABR letter:
  - Approval date (AuthorizationActionDate as MM/DD/YYYY)
  - Admin approver first and last name
  - Admin approver organization
  - Admin approver phone
  - Admin approver email

**Comment by steveoh** [comment]
These items were not documented to be stored in the database in the issues for the approval process

> Admin approver first and last name
> Admin approver organization
> Admin approver phone
> Admin approver email

**Comment by nathankota** [comment]
Okay, I mistakenly thought it was stored during the current (to-be-altered) generation of the ABR letter:
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/bd199c72-f9c6-4ae6-a8cb-c8e62cbdfeb6)


This requirement surfaced to suit the purpose of showing the initial approver information when any admin downloads an ABR+inventory report anytime _after_ approval. Should I add a new issue for storing this approver data as a precursor to this issue?

**Comment by steveoh** [comment]
Nope, that ARB page has been deleted and was using the current logged in users account's information.

My intention was not to have you create more issues but to help you realize the items necessary when creating them. Creating good issues are hard and I hope feedback like this helps to improve them.

**Comment by nathankota** [comment]
@rsparker-utah, 

following the comments above regarding,

> These items were not documented to be stored in the database in the issues for the approval process
 > Admin approver first and last name
 > Admin approver organization
 > Admin approver phone
 > Admin approver email

Since we had not previously defined the admin approver info to be stored in the app database nor transferred to the UIC database (#284), this will not be implemented on the inventory review page. I have validated that the `Approved` status is there. 

Do you agree that this task/issue is accepted and ready to be closed?

**Comment by nathankota** [comment]
Similar to #275, I was not seeing this until just now. Validated.

![Image](https://github.com/uic-utah/uic-inventory/assets/15659642/798bcab0-ae83-49d3-b031-aa2df3c7ecee)
