### ISSUE TITLE
Disable 'approve' and 'reject' buttons for authorized inventories

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#280]
#### After an inventory is approved, disable the `Approve` and `Reject` buttons on the Inventory Review page. They can remain visible to admins.

-------------------------------------------------------------
Notes:
- All of the data necessary to generate/print the ABR letter will already be stored and displayed on the Inventory Review page (#279), so there is no justifiable reason (that can be thought of at the moment) to re-approve an inventory. 
- Since admins can edit app data after an inventory is approved (#272), if a post-approval change needs to occur, an admin can make edits to both the app and the UIC database for synchronization, and those changes should appear on a newly-printed ABR+inventory report.

**Comment by steveoh** [comment]
i moved this into the inventory to condense these small issues
