### ISSUE TITLE
Firewalls to access UIC db from UIC google project

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#283]
- [x] Dev: [RITM0257432](https://utah.service-now.com/nav_to.do?uri=sc_req_item.do?sys_id=33af0fea87d2f5142a1a21b8cebb35d3)
- [x] Prod: [RITM0257434](https://utah.service-now.com/nav_to.do?uri=sc_req_item.do?sys_id=279117228716f5142a1a21b8cebb3575)

**Comment by nathankota** [comment]
@steveoh, which port type? 

If "Specific", then need to define udp/ or tcp/ port #

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/fe180f8b-c148-439e-9265-4f1b19b2ff7d)

If "Ping/ICMP" or "Any", then no port specified

![image](https://github.com/uic-utah/uic-inventory/assets/15659642/e8717770-e980-4a22-86b2-b004c4c90f69)

**Comment by steveoh** [comment]
This would be a question for @rsparker-utah, but I think I know the answer. Since it's a sql server database I'll assume dev is tcp/52528 and dev is tcp/1433.

**Comment by rsparker-utah** [comment]
I have reference to a "52528" port number for the UIC dev environment in my notes, but unfortunately I don't have any port information for the UIC production environment. I also can't seem to find anyway to look up this information in SQL Server Management Studio. I originally got the reference to port 52528 from Michael Foulger, so he may be able to help us track down this information.

**Comment by nathankota** [comment]
Michael confirmed prod, and is checking with dbase to make sure about dev. I'll edit this comment when we have a response/confirmation.

----------------------------
**prod:** tcp/1433
**dev:** tcp/

**Comment by nathankota** [comment]
cloud run app can access the UIC database
