### ISSUE TITLE
Inventory Report - Add Water System Information to Inventory Report Layout

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#287]
Apologies, I missed this during my initial review. Please add a section for "Water System Information" to the Inventory Report Layout after the "Well Information" section.

Water system information example for reference:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/112af355-2751-4705-8d93-2379e515f9ce)

If there is no water system info, please add the following text in in the "Water System Information" section of the report indicating there is no water system information:

 "Not applicable. The well(s) in this inventory do not intersect a source water protection zone."

**Comment by steveoh** [comment]
This is ready for validation

**Comment by nathankota** [comment]
validated
