### ISSUE TITLE
Welcome page - unauthenticated layout

### ISSUE THREAD

**Issue by steveoh** [uic-utah/uic-inventory#29]
what do we want to show on the main page?

**Comment by nathankota** [comment]
WIP - more input needed from UIC staff

### [Miro page](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457358735041629&cot=14)

**Comment by nathankota** [comment]
UIC staff have made some changes to the welcome page on the Miro and have indicated that they are done.
