### ISSUE TITLE
Reconfigure ID workflow

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#290]
- [x] Remove the ID creation and display feature #259 
- [x] ID field should still show up in the Inventory Report and ABR letter
- [x] Enable editing of the ID field on the Inventory Review page by admin users
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/707e7093-f599-427c-ab8d-3ca318ee1488)
- [x] Nullify the ID field in test

**Comment by rsparker-utah** [comment]
Tested and confirmed this is working as expected ([site 123 inventory 230](https://uic-inventory.dev.utah.gov/review/site/123/inventory/230)). I was able to edit the ID field on the Inventory Review page and also confirmed the ID was populating in the Inventory report and ABR letter. This issue can be closed, thank you.
