### ISSUE TITLE
Enable new inventory statuses for UIC reviewers

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#292]
UIC reviewers would like to track the review process more closely by adding three new inventory statuses, and the ability for admin users to change the statuses on the Inventory Review page. 

The new statuses and their sequence can be found at 
https://lucid.app/lucidchart/5ad270d8-4aa9-47d9-a66b-8ecfb30d743e/edit?viewport_loc=416%2C79%2C1780%2C843%2C86fjXBGtFIbX&invitationId=inv_02a5a3b4-5dfe-46e5-ad2d-446caaa7dd49

With each status change, the following should occur:
- [x] Status change notification
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/34d538db-cb1d-4bbb-9b42-f45337c520ac)
- [x] Bell notification
- [x] Status appears on the inventory table
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/1315478a-cf20-463d-892b-c468aeafd60a)

- [x] Status appears in the top left of the Inventory Review page (like the Approved status already does)
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/840dc722-3a69-4d65-b0e8-fb741fd3bef6)

- [x] The reviewer that changed the status and the date of the change are stored
- [x] Click on status icon on review page to show:
  - name of reviewer that changed the status
  - date of status change 
 
![image](https://github.com/uic-utah/uic-inventory/assets/15659642/c837da6f-a062-4923-9381-3f7677fd2310)

- [x] The ABR letter is generated with the inventory doc download for statuses of Approved, Authorized, Completed.

(**NOTE:** #54 has been updated to include the new statuses)

**Comment by nathankota** [comment]
@rsparker-utah my testing is complete, and I think it is working as expected. Awaiting your validation.

**Comment by rsparker-utah** [comment]
@nathankota The new inventory statuses are working as expected for me as well (the functionality is awesome, thanks Steve!). This issue can be closed.
