### ISSUE TITLE
ID and Edocs validation at inventory approval

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#293]
Check that the ID (#290) and Edocs fields are populated before the status can be changed from Approved to Authorized.
If either the “ID” or “EQDocs #” fields are null:
- the status does not change to Authorized, and
- display a notification that “The ID or EQDocs # field is blank. These fields must be populated before the inventory can be authorized.”

**Comment by nathankota** [comment]
tested and validated with:
- [Site 80, inventory 145](https://uic-inventory.dev.utah.gov/review/site/80/inventory/145) with no Edocs
- [Site 50, inventory 180](https://uic-inventory.dev.utah.gov/review/site/50/inventory/180) with no Edocs or Id
- [Site 62, inventory 171](https://uic-inventory.dev.utah.gov/review/site/62/inventory/171), various missing and modifying data scenarios

Awaiting confirmation from @rsparker-utah

**Comment by rsparker-utah** [comment]
I Tested each of the following scenarios using [site 123, inventory230](https://uic-inventory.dev.utah.gov/review/site/123/inventory/230) when going from an "Approved" inventory to an "Authorized" inventory:

- Verified the validation check for EDocs # field is working correctly when the EDocs # field was null and the ID field was populated (i.e., inventory status would not change to "Authorized" and validation message was displayed notifying the user),
- Verified the validation check for ID field is working correctly when the ID field was null and the EDocs # field was populated (i.e., inventory status would not change to "Authorized" and validation message was displayed notifying the user),
- Verified the validation checks were working when both the EDocs # and ID fields were null (i.e., inventory status would not change to "Authorized" and validation message was displayed notifying the user),
- Verified the validation checks were working when both the EDocs # and ID fields were populated (i.e., the inventory successfully authorized and no error messages were displayed)

I did come across one issue regarding the Edocs# and ID field checks triggering when going from "Submitted" to "Approved" and have detailed it in a separate issue (i.e., #302 ); however, for this issue I can confirm the validation checks are working correctly when going from "Approved" to "Authorized" statuses.

**Comment by nathankota** [comment]
@rsparker-utah , @steveoh The title of this issue does not quite match the intent, which is my fault. I agree with Ryan that this works as expected when transitioning from Approved to Authorize, but the title was misleading and suggests that the edocs and ID checks should be in place when changing from Submitted to Approved (i.e. "at inventory approval"). I will close this and might add some notes or slight edits to #302 .
