### ISSUE TITLE
Unable to add a Regulatory Contact to a New SER Inventory for a Site that has an Existing "Submitted" (or Beyond) Status Inventory associated with it

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#305]
There is currently a workaround for this issue and it is not a show stopper, but I wanted to add it as a parking lot item to address/review in the future. 

A public user is unable to submit a new SER Inventory to an existing site if it has the following criteria:

- The site has an existing non SER inventory with a "Submitted" (or beyond) status, and
- The site does not have an existing regulatory contact

This issue has to do with the public editing rules established in #143 , specifically:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/09fa499d-02fc-416c-aa5e-28d734b7f2f1)

The public user is still able to fill out the rest of the information for the new SER inventory and it shows up in the app as "Draft" status under the site, but since the user is unable to add the required regulatory contact, they are unable to submit it.

The functionality is currently working as outlined in #143 , but the inability for a user to add a new SER Inventory to an existing site that meets the aforementioned criteria may cause confusion in the future. 

I don't yet know the best way to approach this, but potentially allowing users to add new contacts (or at least regulatory contacts) to their existing sites with Inventory Statuses = Submitted and beyond may be one approach. 

For reference, the current proposed workaround for the above scenario is as follows:

1. Instruct the user to create the draft SER Inventory and send the associated regulatory contact information to a UIC Admin user,
2. The UIC Admin user then manually adds the submitted regulatory contact to the existing draft SER inventory,
3. The UIC Admin informs the user that the regulatory contact has been added and the user can then sign/submit the inventory.

**Comment by steveoh** [comment]
The workaround seems like a poor solution. Can we come up with a more intuitive approach that doesn't allow the inventories to get fouled up during the submission?

**Comment by rsparker-utah** [comment]
Definitely, that sounds good. I'm thinking for situations like this if we could allow the user to add a regulatory contact during their SER well creation and then have a bell notification notifying UIC Admins that the new regulatory user had been added, that would be sufficient. 

As a side note, the reason I'm thinking allowing the addition of just the regulatory contact (as opposed to all contacts) will suffice in this situation is that I have created several update forms for folks to submit to us if they need to make changes post submission. One of these forms is for submitting the addition of another contact to an existing facility, so there is a means to add contacts post inventory submission via a form.

I'm open to other suggestions as well though.

**Comment by nathankota** [comment]
#### Exception/change to regulatory community editing rule #143:

- The only allowable edit to a Site after the first Well Inventory has been submitted is: A Regulatory Contact can be added to a Site (most commonly when creating a new draft SER inventory)

When a Regulatory Contact has been added to a Site with a submitted inventory, a bell notification should occur, e.g. _NK added a regulatory contact for the approved site 123_

**Comment by steveoh** [comment]
This is read for validation

**Comment by rsparker-utah** [comment]
Validated, this looks good.
