### ISSUE TITLE
Status Change Confirmation Messages Adjustments

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#306]
Could we adjust the verbiage for the following confirmation messages:

### For the "Approve Submission Confirmation" message
(i.e., going from "Under Review" to "Approved")

Could we please adjust the verbiage from:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/d68d4889-9bda-4311-b93e-e21215cb13c9)

to:
"Has the inventory been reviewed and is it ready to be approved?", for example:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/a4fe7015-b37d-431f-95cf-3a914f492b1a)

### For the "Authorize Submission Confirmation" message
(i.e., going from "Approved" to "Authorized")

Could we please adjust the verbiage from:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/c38154d7-9533-43d1-82be-3dc1db02808d)

to:
"Has the inventory information been entered into the UIC geodatabase?", for example:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/b2ba3287-b19c-41c8-ae4d-09e7832a7857)

**Comment by steveoh** [comment]
This is ready for validation

**Comment by rsparker-utah** [comment]
Validated, the updated messages look great, thanks!
