### ISSUE TITLE
Unable to See Admin Reviewer Information on Inventories Reviewed By Other Admins

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#308]
There may be a bug that is preventing me from seeing the stored reviewer information for other UIC Admin users. For example, for site 124:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/88437594-429f-4d7f-b250-f7d950953d50)

If I click on any of the inventories that have an admin review status, I am unable to see the stored information for the admin user that reviewed the inventory at the specific status step. Examples include:

"Under Review" Inventory associated with site 124:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/827cd4c1-8433-40e5-b88c-b8602621e20f)

"Approved" Inventory associated with site 124:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/55f17ac6-eaae-4cb3-bcd6-fe2ebff21bad)

"Authorized" Inventory associated with site 124:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/99bbeefa-9a94-4a85-92ce-b42455bd3667)

"Completed" Inventory associated with site 124:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/176aa789-8cb4-4252-8d2f-804408eb5169)

As a side note, site 124 is not a site that I had created or had previously interacted with (i.e, done any sort of admin review on).

**Comment by steveoh** [comment]
This is ready for validation

**Comment by rsparker-utah** [comment]
I am now able to see other UIC Admin reviewer information, this issue is resolved. Thanks!
