### ISSUE TITLE
Remove "null" text from the "Address" box for Regulatory Contacts in the generated Inventory Report

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#315]
The "Address" box for Regulatory contacts under the "Site Contacts" section in the Inventory Report is currently displaying "null":
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/6f8e913b-fb75-44ff-9844-7575b24fbca2)

Could we please remove this "null" text in the "Address" box for Regulatory Contacts in the Inventory Report so that it is just blank? For example:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/14a95d45-63b2-41f2-8c74-cac6811a0248)

**Comment by nathankota** [comment]
validated
