### ISSUE TITLE
Update Order Number and Payment Instructions on the Well Inventory Page

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#317]
I've been informed that the payment application we use for UIC has been updated (as of 5/15/2024) from:

https://secure.utah.gov/cart/dwq_cart/details.html?productId=205)

 to:

https://secured.utah.gov/dwq/Forms/Page/dwq-market/dwq-market/?id=205

This update will affect the following two areas on the "Well Inventory" page of the UIC web app:

- The "UIC inventory form order number" field:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/d9ccbc38-ff9f-4385-8c66-3a8b6974a431)

- And the popup instructions associated with the "Click for instructions" hyperlink:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/19a11407-69d8-475b-94fe-4d32ce078b13)

This new payment application will have a 36 digit alphanumeric GUID order number (replacing the existing 7 digit order number) that is sent to the user after they complete a purchase, for example: 
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/76913404-eedf-42cb-b011-fa846f0ee00c)

Our division has opted to instruct users to use the first 8-digits of this GUID when reporting the order number on payment forms. Due to this change, could we please do the following:

On the "Well Inventory" page:

- Update the validation check for the "UIC inventory form order number" field to accommodate this new 8-digit alphanumeric order number format, example: **5afdc8ff**
- Update the text in the popup instructions associated with the "Click for instructions" hyperlink to the following (in accordance with the updated [payment application](https://secured.utah.gov/dwq/Forms/Page/dwq-market/dwq-market/?id=205)):

1. Navigate to this website: https://secured.utah.gov/dwq/Forms/Page/dwq-market/dwq-market/?id=205
2. In the “Item” field drop-down menu, select the option for “UIC Inventory Review”.
3. Enter the number of sites (**not** the number of injection wells) in the Quantity box for which you are submitting the UIC Inventory Review Fee.
4. In the “Facility/Site Name from UIC Inventory Information Form” box, enter the Site Name. This should match the Site Name provided on the first page of the UIC information form.
5. Complete the “Contact Information” section and click “Continue To Payment” to proceed to payment.
6. After completing the payment process you will receive an order number. Return to this page and enter the first 8 digits of the order number as the UIC inventory form order number.

**Comment by nathankota** [comment]
Validated. @rsparker-utah please confirm, then I believe you can close the issue since you created it.

**Comment by rsparker-utah** [comment]
Validated. Tested this using both my admin and public user accounts and it was working as expected. Thanks Steve!
