### ISSUE TITLE
Add Notification Text Regarding Consequences of an Inventory Rejection

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#318]
Could we revise the text under the "Sign and Submit Inventory" heading on the Submit page:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/95f7c83c-a481-4a4f-a468-f6c8754d817a)

 To the following: 

_In accordance with Section R317-7-6.4(C) of the Utah Administrative Rules for the Underground Injection Control Program, providing a signature other than the owner, operator, or legal representative - and/or submitting an application with insufficient information - may result in the rejection of the application. Rejected applications will be removed from the system and will need to be resubmitted with complete information to be considered for review._

This recommendation was presented to me while chatting with a colleague, with the goal of notifying users of the consequences if an inventory is submitted without a correct signature and/or does not have adequate information to review.

**Comment by rsparker-utah** [comment]
@nathankota I like the wording you recommended:

> _In accordance with Section R317-7-6.4(C) of the Utah Administrative Rules for the Underground Injection Control Program, providing a signature other than the owner, operator, or legal representative - and/or submitting an application with insufficient information - may result in the rejection of the application. Rejected applications will be removed from the system and will need to be resubmitted with complete information to be considered for review._

I'll run this by my team to get their thoughts. In the meantime, I've updated my original comment to reflect this updated texct.

**Comment by rsparker-utah** [comment]
@nathankota I spoke with Porter and we both think the text you proposed is good. I've updated my original issue text to include this updated text. Thanks Nathan

**Comment by steveoh** [comment]
This is ready to be validated

**Comment by rsparker-utah** [comment]
Validated, thanks Steve
