### ISSUE TITLE
Delete Site

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#32]
I would like to be able to delete a Site if I no longer want/need it in my list.

**Comment by steveoh** [comment]
Any site can be deleted now. I will add the site status and the deletion requirement next. 

I think the status of incomplete maybe not the right deletion requirement. It seems that a user should be able to delete anything other than authorized possibly?

**Comment by nathankota** [comment]
Agreed - only "Authorized" cannot be deleted by user.

**Comment by nathankota** [comment]
(issue edited based on most recent comments)

**Comment by steveoh** [comment]
Deleting a site has been available for a few releases but the inventory and status part have not been built yet.

**Comment by nathankota** [comment]
should I go ahead and validate the functionality without the status part?

**Comment by steveoh** [comment]
might as well.
