### ISSUE TITLE
Bell Notification Icon Missing From Menu Bar in the Production Environment

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#330]
We've been preparing resources and getting things organized to go live with the UIC web app within the next week or so (go live has been delayed due to staff being out of the office). During this preparation, I noticed the Bell Notification Icon/Menu is currently missing in the production environment, for example:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/a303534f-846c-471f-8ae2-a00fea656d52)

Here is an example image of the menu bar with the Bell icon for reference:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/fe9fa85f-864f-47ab-9b78-07dd8fffa817)

**Comment by steveoh** [comment]
You only see that if you are an admin with notifications turned on.

**Comment by nathankota** [comment]
@rsparker-utah since you have an "elevated" role you can click on the Account tab in the header, select your profile, turn on and save the notifications setting, then refresh and you'll see the bell.
