### ISSUE TITLE
UIC Web App Test Environment Unavailable

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#335]
The UIC Web app test environment url (https://uic-inventory.dev.utah.gov/) is returning a "Service Unavailable" error, for example:
![image](https://github.com/uic-utah/uic-inventory/assets/49735267/df85c273-19d7-4a9b-b87e-b4386325de15)

**Comment by steveoh** [comment]
We shut down all the cloud items that were costing money since we weren't actively testing.

**Comment by rsparker-utah** [comment]
Ah gotcha, that makes sense and we definitely appreciate the cost savings! I'll make a note of this and close this issue. Thanks!

**Comment by steveoh** [comment]
We can spin it back up whenever you need though if you want to test something more extensively.
