### ISSUE TITLE
Ground Water Field Not Populating For Wells Added by an Admin User

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#347]
We've run into a potential issue/bug while reviewing submitted inventories within the UIC web app. It looks like the Ground Water field is not populating when an admin user adds a well to an inventory. This issue/bug was identified during review of the following inventory:

https://uic-inventory.deq.utah.gov/review/site/27/inventory/24

An explanation of this issue is as follows:
The inventory in question was submitted by a standard user. While the inventory was in the "Authorized" status, it was noticed that several of the wells were placed in the wrong location and had the wrong operating status according to the well detail documents submitted with the wells. We used our admin permissions to remove the incorrect well locations and re-add them in the correct location using the following workflow:

1. Navigated to the [Well Location page](https://uic-inventory.deq.utah.gov/site/27/inventory/24/add-wells) for the site,
2. Clicked the garbage can icon to remove each well,
3. Re-added each well in the correct location,
4. Clicked the "Next" button to go to the [Well Details page](https://uic-inventory.deq.utah.gov/site/27/inventory/24/add-well-details),
5. Selected all of the re-added wells, re-added the associated well details documents, and clicked the "Update" button.

We then navigated back to the [inventory review page for the site](https://uic-inventory.deq.utah.gov/review/site/27/inventory/24) and noticed that the "Ground Water" field in the "Location Details" section did not populate for these re-added wells (i.e., the Ground Water field displayed "unknown", whereas before we updated these wells it had been displaying the GWZ/ARDA icons). For example, here is a screen shot of the Well Information section of the inventory report for this site before the wells were removed and re-added:
![image](https://github.com/user-attachments/assets/98619fb4-8346-49de-bbf5-e5e598e807e4)

And here are screenshots of the Location Details section of the inventory review page and associated Well Information section of the inventory report after the wells were deleted and re-added for comparison:
![image](https://github.com/user-attachments/assets/1122fa54-1d10-44fd-9d9e-240e2a579571)

![image](https://github.com/user-attachments/assets/81a1db9e-a406-4015-a3e7-cf1cd6a80e3e)

The updated well locations were only slightly different from the original locations, so I don't think the location change is what's causing the discrepancy for the Ground Water designations. Here is a before and after update location comparison image for reference:
![image](https://github.com/user-attachments/assets/ea2cb010-11ac-476e-b1f9-9e93a69c2d8b)

**Comment by steveoh** [comment]
The groundwater extractions happen when an inventory is submitted. If the inventory was already submitted when you created the wells then the code never ran to extract that information. We'll have to think about how this should work if it will be a regular occurrence.

**Comment by rsparker-utah** [comment]
Quick update, I've chatted with my colleagues about the concept of keeping things as they are, but then adding a button (or similar) that would allow us to trigger the ground water check as needed. We liked this idea and are interested in pursuing this kind of functionality if possible.

**Comment by steveoh** [comment]
Ok. Where would you expect this to be?

**Comment by rsparker-utah** [comment]
I had envisioned it on the Inventory Review page, for example something along the lines of:
![image](https://github.com/user-attachments/assets/68843cad-48d5-4816-a664-6a9a9aca8a87)
I'd be open to other suggestions as well.

**Comment by steveoh** [comment]
@rsparker-utah this is ready to test. You should see this in the dev environment.

<img width="186" alt="image" src="https://github.com/user-attachments/assets/f2c9fb61-6061-483e-9ebf-1edd166633df">

**Comment by rsparker-utah** [comment]
@steveoh I ran through some testing and everything was working great (the refresh icon button is perfect)! We're ok with this update being pushed to the production environment at your convenience. Thanks so much!

**Comment by steveoh** [comment]
deployed.
