### ISSUE TITLE
Allow 3rd party entities to upload owner/operator or legal representative signature

### ISSUE THREAD

**Issue by steveoh** [uic-utah/uic-inventory#348]
## Update “Sign and Submit” page with the following:

![image](https://github.com/user-attachments/assets/0b1b292c-4d74-4ee1-8faf-efc4c17921c1)

- [x] Update the verbiage to notify users that an owner or legal representative signature must be uploaded to sign/approve the inventory,
- [x] Add a link to a [UIC Inventory Submission Signature Template_DRAFT.pdf](https://drive.google.com/file/d/1LXQ_gYYbqQrljmiEM9vPwEfMulGopkWl/view?usp=drive_link) (exact verbiage and format of this template subject to change) that users can use to collect signatures,
- [x] Add a document upload box (similar to the one on the “Well Details” page?) allowing users to submit the completed [UIC Inventory Submission Signature Template_DRAFT.pdf](https://drive.google.com/file/d/1LXQ_gYYbqQrljmiEM9vPwEfMulGopkWl/view?usp=drive_link)
- [x] Add a validation check/message that prevents users from clicking the “Submit” button if no signature document has been uploaded to the document upload box.

## Update the Inventory report with the following:

![image](https://github.com/user-attachments/assets/0d094312-5a2e-42b4-a887-2b15466ac34c)

- [x] Include the signed [UIC Inventory Submission Signature Template_DRAFT.pdf](https://drive.google.com/file/d/1LXQ_gYYbqQrljmiEM9vPwEfMulGopkWl/view?usp=drive_link) in the Inventory report. Provided using this separate signing page makes sense, we would then likely need to adjust the “Inventory Details” section of the Inventory Report, specifically the “Signed By” and “Signed Date” fields (e.g., remove or re-label):

https://docs.google.com/document/d/1X3dfm9eLRMjZTlb2dsSxKOjXdHWucq4TJTcyigoXhQk/edit

**Comment by steveoh** [comment]
@rsparker-utah are you happy with this UI so far?

<img width="805" alt="image" src="https://github.com/user-attachments/assets/cfba498b-b5b0-4599-838f-fe7c23930dcd">

**Comment by rsparker-utah** [comment]
@steveoh Yes, this looks great! I have one minor text edit request. Could we adjust the text slightly in the first sentence from:
This UIC Inventory Information Form must be signed by the **owner**, **operator**, or **legal representative's** of the injection well(s) for which the inventory information is being submitted.
To:
This UIC Inventory Information Form must be signed by the **owner**, **operator**, or **legal representative** of the injection well(s) for which the inventory information is being submitted.

**Comment by steveoh** [comment]
Yep sorry. I made that change since it was plural later on. Easy fix!

**Comment by steveoh** [comment]
@rsparker-utah I spun up the dev project and pushed these there. Would you mind giving it a spin and see what you think. The file uploads take a minute to get scanned and migrated to the cloud function so if the pdfs aren't available instantly give it a minute and try again.

**Comment by rsparker-utah** [comment]
@steveoh We were able to run through this new functionality and it was working well. We think this will work nicely, thank you! 

I was also able to confirm in the test environment that old inventories (i.e., inventories that were processed through the system before the signature update went into effect) will fail to download after the update is made. There are currently inventories at the following varying statuses (in the prod environment):

Draft - 5
Submitted - 1
Under Review - 2
Approved - 3
Authorized - 1
Completed - 6

I don't foresee this being an issue for inventories that have already been processed (i.e., inventories with a status = "Completed"), since we store copies of the generated completed Inventory Packets in our document management system. The inventories at other statuses may need some further consideration (e.g., should we wait until all these are processed and "Completed" before implementing the update or is there another work around we could consider?).

**Comment by steveoh** [comment]
@rsparker-utah I can take a stab at treating the previous submissions as a part of this fix and make them both succeed. That will make old redownloads continue to work. Or we can wait. I think it's your call.

**Comment by rsparker-utah** [comment]
@steveoh Ok, that would be great if you wouldn't mind looking at the previous submissions as part of this fix.

**Comment by steveoh** [comment]
@rsparker-utah I believe this is performing how you expect. Please verify and let me know how to proceed.

**Comment by rsparker-utah** [comment]
@steveoh I was able to run through some testing in the dev environment. Quick summary of my testing workflow:

1. I created a new site/inventory (i.e., [site 164, inventory 321](https://uic-inventory.dev.utah.gov/review/site/164/inventory/321)) and verified again that the signature update was working as expected,
2. I then tested downloading inventory packets from both sites/inventories created after the 3rd party signature functionality was updated (i.e., [site 164, inventory 321](https://uic-inventory.dev.utah.gov/review/site/164/inventory/321) and [site 161, inventory 317](https://uic-inventory.dev.utah.gov/review/site/161/inventory/317)) and sites that were created before the 3rd party signature functionality was updated (i.e., [site 156, inventory 308](https://uic-inventory.dev.utah.gov/review/site/156/inventory/308) and [site 138, inventory 275](https://uic-inventory.dev.utah.gov/review/site/138/inventory/275)). 

The inventories downloaded successfully for all of the above test sites/inventories. I noticed one potential minor formatting bug as I was writing up my testing workflow. It looks like the "Location Details" heading is being duplicated across the first and second pages of the Inventory Information Report, for example:
![image](https://github.com/user-attachments/assets/5588c728-c3f1-47e6-a1e5-cb2af44f2127)

Other than that, things are looking great. Thanks again for implementing the extra inventory packet download fix!

**Comment by steveoh** [comment]
When would you like this pushed to production?

**Comment by rsparker-utah** [comment]
@steveoh We're good to have the fix pushed to production at your earliest convenience. Thanks!

**Comment by steveoh** [comment]
@rsparker-utah this was just deployed to production,
