### ISSUE TITLE
Unable to Download Signature Attachment Sheet Via The Attachment Hyperlink

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#356]
We've come a cross a bug that we missed during testing of the 3rd party signature update (#348). The signature page is not downloading and an error message is displayed if the signature attachment hyperlink is clicked on the Inventory Review Page.

For example on the Inventory Review page for [site 46, inventory 44](https://uic-inventory.deq.utah.gov/review/site/46/inventory/44), when the signature attachment hyperlink is clicked:
![image](https://github.com/user-attachments/assets/81db0f1f-fd59-482d-bd31-54bbdcc209b3)

The browser directs to: https://uic-inventory.deq.utah.gov/api/site/46/inventory/44/signature.pdf

and the following error message is displayed:
![image](https://github.com/user-attachments/assets/f3a4786d-f42d-4321-af8a-b9effa8dc94a)

The signature page is showing up fine when the Inventory Report is downloaded, so this seems to just pertain to the signature attachment hyperlink on the Inventory Review Page.

**Comment by steveoh** [comment]
thanks for noticing. This is corrected in production.
