### ISSUE TITLE
Inventory Packet Formatting Request

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#365]
We've noticed a bug in the "Site Contacts" section of the generated Inventory Report where if there is more than one listed contact, the  label for the "Organization" field is being wrapped such that there is a dangling "n", for example:
![image](https://github.com/user-attachments/assets/55e05103-a2f7-450b-a78a-444cb2e03110)

This dangling "n" does not seem to happen if there is only one contact.

From what I can tell, this bug seems to have been introduced sometime after 8/29/2024 i.e., the formatting of the "Organization" field in Inventory Reports with multiple contacts generated on or before 8/29/2024 are fine, but Inventory Reports generated after 8/29/2024 are showing the dangling "n". As an example, I compared an Inventory report for https://uic-inventory.deq.utah.gov/review/site/32/inventory/32 generated on 8/29/2024 with one that I re-generated on 10/16/2024. The report generated on 8/29/2024 does not have the dangling "n" and the report generated on 10/16/2024 does have the dangling "n":

![image](https://github.com/user-attachments/assets/f8bd1056-46fd-4799-9510-39c3329fa614)

Would it be possible to adjust the formatting of the "Organization" field in the "Site Contacts" section table for Inventory Reports containing more than one contact so that the "n" is no longer dangling?

**Comment by rsparker-utah** [comment]
Quick fyi, it looks like this formatting issue is happening in other table cells within the report, for example:
![image](https://github.com/user-attachments/assets/6bf92463-77a9-4040-bddb-ab992d149d75)
I've updated the issue name due to this discovery.

**Comment by steveoh** [comment]
@rsparker-utah I deployed this to production today. Do you want to validate and close this after testing it?

**Comment by rsparker-utah** [comment]
Looks great! Validated, thanks Steve!
