### ISSUE TITLE
Unable to Generate Inventory Packet

### ISSUE THREAD

**Issue by rsparker-utah** [uic-utah/uic-inventory#369]
We've run into an issue where the Inventory Report for [Site 64, Inventory 69](https://uic-inventory.deq.utah.gov/review/site/64/inventory/69) is failing to generate/download. The Inventory Report looks like it begins to process when we click the "Download" button (i.e., the icon spins next to the "Download" button):
![image](https://github.com/user-attachments/assets/0ebf8423-5171-40bf-ac8b-1699b802aaec)

However, after a minute or so it stops and there is a red "!" next to the "Download" button and we are unable to download the completed ABR letter/report:
![image](https://github.com/user-attachments/assets/460b9a6d-2a03-4ad2-891d-d73a257b7cee)

Could I trouble you to please look into this issue?

As a side note, we've tried downloading a few other Inventory reports (e.g., [Site 79, Inventory 85](https://uic-inventory.deq.utah.gov/review/site/79/inventory/85) and [Site 69, Inventory 75](https://uic-inventory.deq.utah.gov/review/site/69/inventory/75)) and these seem to work fine which makes me think the issue may be specific to [Site 64, Inventory 69](https://uic-inventory.deq.utah.gov/review/site/64/inventory/69).

**Comment by steveoh** [comment]
I'm seeing errors that the file size is too large. The other inventories are probably fine since they don't have all of the attachments.

<img width="454" alt="image" src="https://github.com/user-attachments/assets/265a925c-a9d0-4a3e-be43-946b713e33bb">

**Comment by rsparker-utah** [comment]
Ah! That makes sense. If I'm understanding correctly, it sounds like the system is able to ingest the pdfs fine, but the function that compiles the ABR letter/inventory report is the bottleneck due to the total size of the pdfs. Do you think we'll need to consider limiting the total size of attachments up front or are there potential workarounds with the function that we could leverage?

**Comment by steveoh** [comment]
I'm going to look into optimizing the pdfs some. Or we may have to change the download function.

**Comment by steveoh** [comment]
@rsparker-utah this is ready for a validation in production. I pushed it to prod to test with the large pdf example project. 

The solution was storing the report in cloud storage and creating a signed url directly to the file that is only valid for 10 minutes. I set a lifecycle policy on the cloud storage to delete the files after 2 days so they don't build up. Every time you click download a new file and 10 minute link is generated. This allows you to view the pdf or anyone you share the link with for up to 10 minutes. If that is too short, please let me know and I can increase the time.

**Comment by rsparker-utah** [comment]
@steveoh Awesome, this sounds like a great solution! I think the 10 minute link share window is adequate (I'll double check with my colleagues to verify this). 

I've had a chance to do a few tests. The download tests for the following sites/inventories worked great:
https://uic-inventory.deq.utah.gov/review/site/85/inventory/94
https://uic-inventory.deq.utah.gov/review/site/91/inventory/103

I then tried the following sites/inventories, but the download did not complete (i.e., the spinning download icon showed up after clicking the download button and it seemed to be processing for a bit, but then it displayed the red exclamation point and the download stopped):
https://uic-inventory.deq.utah.gov/review/site/86/inventory/95
https://uic-inventory.deq.utah.gov/review/site/88/inventory/102

I'm not sure if this is relevant, but the the inventory reports that successfully downloaded were for Approved and Completed status inventories. The inventory reports that failed were both for Authorized status inventories.

**Comment by steveoh** [comment]
Good catch. Those are two different reports right? One is ABR and the other is something else?

**Comment by rsparker-utah** [comment]
I think they are all the full ABR/Inventory Reports.

**Comment by steveoh** [comment]
Ok, so digging through the logs...

1. site 88 inventory 102 has an encrypted PDF. I can ignore the encryption but I'm not sure how that will affect the report pdf. I guess we can find out.
2. site 86 inventory 95 is hitting a time out setting I created. It has a lot of attachments etc and I will need to increase the time allowed. 

I will comment here after I push these changes to production.

**Comment by steveoh** [comment]
I believe this is working now. I also think the encrypted PDF is showing up blank. How do you want to proceed with those?

**Comment by rsparker-utah** [comment]
Thanks so much Steve! Both 

- https://uic-inventory.deq.utah.gov/review/site/86/inventory/95
- https://uic-inventory.deq.utah.gov/review/site/88/inventory/102

are working now. Regarding the encrypted PDF showing up blank, is there anyway to address this automatically through the ABR/Inventory Report compilation process?

If not, we can implement a manual step on our end during the processing of inventories to check for encrypted documents, remove the encryption (via manually printing the document to pdf), and then manually appending this file to the generated ABR/Inventory Report.

**Comment by steveoh** [comment]
Ok, I added some code to hopefully remove encryption when signatures are uploaded. I replaced this inventories signature with the version i tested on. Ideally any future adobe sign encryption will be handled by the application. This is ready for another sign off. Let me know if you find any problems or go ahead and close as complete.

**Comment by rsparker-utah** [comment]
Sounds good, thanks Steve. This is working great now and I feel comfortable closing this issue.

**Comment by rsparker-utah** [comment]
@steveoh Sorry to open this back up (if you'd prefer a new issue is created, I'd be happy to do that instead), but we came across another inventory today that is failing to download:

https://uic-inventory.deq.utah.gov/review/site/77/inventory/88

Some additional information:

- This inventory looks like it's another one that has an encrypted signature attachment. 
- It also has three well detail attachments (at 911 KB each)
- We refreshed our browser windows and tried the download button a few times to verify the issue (most recent try was around 5:45ish pm on 12/5/2024)
- I tried downloading a couple other inventories and they downloaded fine which makes me think it make just be something with this specific inventory.

Could we trouble you to look into this when you get a free minute? Thanks

**Comment by steveoh** [comment]
This is a different issue. 

> Error: Trying to parse invalid object

One of the PDFs is giving our pdf reader trouble.

**Comment by rsparker-utah** [comment]
Adding a few notes for closing comments:

- The signature pdf seems to have "Password Security" based on the Adobe Acrobat settings, which is likely causing the download issue,
- The signature page was replaced with a non password protected version that enabled the download.
