### ISSUE TITLE
Site Status

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#43]
(updated according to [this comment](https://github.com/uic-utah/uic-inventory/issues/43#issuecomment-1726214904) below)

### Statuses

These do not need to be displayed on the app. The Site statuses follow the statuses of the **first** inventory (#54) associated with that Site. After the first inventory has been approved and ingested into the prod database, the Site contacts can be edited, and the Site status can deviate from the first inventory's status. 

- **Incomplete:** 
    - Missing any required info on the Details, Contacts, or Location pages.
    - All pages are complete, but the **first** inventory associated with the Site has not been submitted. 

- **Complete:** 
    - Details, Contacts, and Location pages have all the required fields completed.

- **Submitted:** 
    - The first inventory associated with the Site has been submitted.

- **Authorized:**
    - The first inventory associated with the Site has been reviewed and approved

- ~**Ingested:**~
    - ~The first Approved inventory (and the parent Site) have been sent to the prod database.~

**Comment by steveoh** [comment]
please list the fields that are required to be considered complete

**Comment by nathankota** [comment]
### [Entered Text](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457361391807395&cot=10)
Site Name `UICFacility.FacilityName`
Land ownership at site `UICAuthorization.OwnerSectorType`
NAICS code `UICFacility.NAICSPrimary`
NAICS title `UICFacility.NAICSTitle`
Name (first and last) `UICContact.ContactName`
Email address `UICContact.ContactEmail`
Phone number `UICContact.ContactPhone`
Organization `UICContact.ContactOrganization`
Street address `UICContact.ContactMailAddress`
City `UICContact.ContactMailCity`
State `UICContact.MailState`
Zip `UICContact.ZipCode`

### [From address point or digitized point](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457358055859217&cot=10)
Street address and city/zip OR coordinates from digitized point `UICFacility.FacilityAddress`
Calculated from address or digitized point:
`UICFacility.CountyFIPS`
`UICFacility.FacilityCity`
`UICFacility.FacilityState`
`UICFacility.FacilityZip`

### [From selected parcel or digitized boundary](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457358055859323&cot=10)
`UICFacility.FacilityID`
`UICFacility.CreatedOn`

**Comment by steveoh** [comment]
This is as done as it can be until we get to the submission phase. The FIPS, FacilityID and CreatedOn are not on my radar. Do those come from the import to prod process or the app somewhere?

**Comment by nathankota** [comment]
`UICFacility.CreatedOn`
This is the date the boundary was created in the app. If it is modified at any time before submission, the CreatedOn date becomes the date it was modified/edited. If that is a PIA, we can come up with an alternative, like keeping it as the first date it was created in the app.

`UICFacility.FacilityID`
Based on the **[rules](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457358055859323&cot=10)** for this, it seems like it will need to be created from the import to prod process, since the UICFacilityGUID won't be created until the shape is imported.

> Auto-generated UTUccFXXXXXXX where cc=countyFIPS; F is automatic; plus last 7 digits of UICFacilityGUID

`UICFacility.CountyFIPS`
This could come from the app as soon as a point is defined (address or digitized) for the location. I imagined it much like Atlas where the address, zip, city and county are all determined by the point. There is a domain for the FIPS already in the prod database, but if the address/point is spatially assessed against [UGRC county boundaries](https://opendata.gis.utah.gov/datasets/utah-county-boundaries/explore), seems like FIPS could come directly from there. 
(Note: If no address found then add WGS Coords to the address field).  
![image](https://user-images.githubusercontent.com/15659642/129218688-d559713c-e07f-4990-967b-684b119ce3fe.png)

**Comment by steveoh** [comment]
If you are referencing the UIC enterprise database, I believe all of those fields are managed by the database.

**Comment by nathankota** [comment]
> This is as done as it can be until we get to the submission phase. The FIPS, FacilityID and CreatedOn are not on my radar. Do those come from the import to prod process or the app somewhere?

Looks like they are [handled by Attribute Rules](https://github.com/uic-utah/uic-attribute-rules/blob/master/src/rules/facility.py) upon importation to the UIC enterprise gdb

**Comment by nathankota** [comment]
> please list the fields that are required to be considered complete

#69

**Comment by nathankota** [comment]
> This is as done as it can be until we get to the submission phase. The FIPS, FacilityID and CreatedOn are not on my radar. Do those come from the import to prod process or the app somewhere?

- FacilityID will now be handled by the app #259 
- FIPS and CreatedOn are attribute rules upon data transfer and import into UIC

**Comment by nathankota** [comment]
@rsparker-utah @steveoh do we need to track all of these Site statuses? The only things we really need to know about Site data is whether it's complete enough to allow an inventory to be added (#69), and if the Site data has been synchronized/transferred to the UIC database, correct? The latter of which is important if new inventories are created for a site that already exists in the UIC database, so as not to duplicate the site (facility) record and only add the inventory data.

**Comment by steveoh** [comment]
I am using incomplete, complete, submitted, authorized, and ingested for sites currently.

**Comment by nathankota** [comment]
@steveoh it sounds like this is implemented and we can close the issue? 

> I am using incomplete, complete, submitted, authorized, and ingested for sites currently.

**Comment by steveoh** [comment]
I do have those values available but am only using complete and incomplete based on contact detail and location status values.
