### ISSUE TITLE
Add Back button

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#56]
> Would it be possible to implement a way to navigate to previous pages while going through the app workflow? For example, a `Back` button (see image for an example).

![210727_Back_Button](https://user-images.githubusercontent.com/15659642/133147320-2da69bc7-e1df-4cdb-8489-703e01296a7c.png)

**Comment by steveoh** [comment]
I don't love this idea but i will do it.

**Comment by nathankota** [comment]
Let me know what your reservations are and I could probably be convinced otherwise

**Comment by steveoh** [comment]
Well, I like to think that the site creation is a wizard and you just complete it in order making tabs a distraction. If you stop and come back the site list will eventually provide you with context of what needs to be completed with links.

**Comment by nathankota** [comment]
I support that, and think I was thrown off by not seeing the Site Details page first, but #55 takes care of that. Closing.
