### ISSUE TITLE
SER - Regulatory Contact

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#59]
### [Miro page](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457354143181920&cot=14)
If `Subsurface environmental remediation wells` is selected as the well subclass type (#19) the user must enter information for the regulatory contact, which will then show up in on the `Site Contacts` page. 

Data field map [here](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457361554139564&cot=10).

**Comment by nathankota** [comment]
Database fields populated:
`UICContact.ContactType` (always "DEQ Project Manager")
`UICContact.ContactName`
`UICContact.ContactOrganization` (need a domain table in the app database for the 5 DEQ Divisions)
`UICContact.ContactEmail`
`UICContact.ContactPhone`

**Comment by steveoh** [comment]
is the idea that they add contacts before they add the well location items?

**Comment by nathankota** [comment]
The initial thought was that they could move beyond this contact section if necessary and come back to it before submitting.

**Comment by steveoh** [comment]
Where does it fit into the data entry flow? Or are you saying you don't care as long as it gets entered.

**Comment by nathankota** [comment]
As long as users are made aware that it is a required field (for SER inventories) before submitting, it does not matter when it gets entered.
