### ISSUE TITLE
GWZ and ARDA check

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#60]
Each well point is assessed for a spatial intersect with two layers:

`Groundwater Zones (GWZ)` 
`opensgid.geoscience.aquifer_recharge_discharge_areas (ARDA)`

---
`UICWell.WellSWPZ` is populated based on the following intersect conditions:

| Value | Condition |
| :-----:| :---------: |
| Y | well intersects GWZ |
| S | well intersects ARDA and not GWZ |
| N | well does not intersect GWZ or ARDA |
| U | (no rule defined for this) |

**Comment by steveoh** [comment]
Whatever has been done for the Groundwater Protection Zones (GWPZ) as far as the enviro app is concerned needs to stay with the enviro app. Bad thing will happen when apps take a dependency on other apps when that isn't a part of their purpose. 

This app will need its own method for querying that protected data. Let's plan to meet with @stdavis at tomorrows dev team meeting and we can reach out to Deidre Beck if necessary to come up with a solution that will work in the cloud for the inventory app.

**Comment by nathankota** [comment]
waiting on #109 and #104

**Comment by nathankota** [comment]
The [Drinking Water Source Protection Zones AGOL item](https://utahdeq.maps.arcgis.com/home/item.html?id=f8e7cb150f984ac29493bf6b41c26d8b) contains a test data set for the GroundWaterZones (GWZ). Long-term management of GWZ in AGOL is TBD.

**Comment by steveoh** [comment]
Since GWPZ is in AGOL do we still need the interconnect to the data center referenced in #109 and #104? Is the ARDA data available in AGOL as well or in the item you linked to?

**Comment by nathankota** [comment]
The ARDA data will not be available in AGOL, so the data center interconnect is still needed for that. 

(Side note: `PWD_ID` was indicated by DEQ as the key between the groundwater data and the ARDA database view, but I am not seeing that field in the AGOL layer. Contacting them now to resolve.)

**Comment by nathankota** [comment]
ARDA layer is in [Open Data](https://opendata.gis.utah.gov/datasets/utah-aquifer-recharge-discharge-areas/explore). 

The interconnect is still needed to access the DDW database to get the water system contact info from the 'vw_water_system_admin_contacts' db view.

**Comment by steveoh** [comment]
Do you think the DDW folks have an API for that or is the database route the preferred method for them?

**Comment by nathankota** [comment]
this
> or is the database route the preferred method for them?

**Comment by steveoh** [comment]
There's no combination to get a U right?

**Comment by nathankota** [comment]
> There's no combination to get a U right?

Right, they were unable to identify any `U` values in the database and, therefore, the rule for it.

**Comment by steveoh** [comment]
Is this waiting on me for anything?

**Comment by nathankota** [comment]
No, sorry, this must have slipped through.
