### ISSUE TITLE
Well Descriptions

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#61]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457354892071672&cot=14) 

- There are three description fields for each well, the requirement for which depends on the well type. Two of the fields offer the option to either enter text or upload a document. 
    - `UICWell.ConstructionDetails` - Required for all wells - enter text or upload doc (2500 characers) 
    - `UICWell.InjectateCharacterization` - Required for SER wells, optional for all others - enter text or upload doc (2500 characers)
    - `UICWell.HydrogeologicCharacterization` - Optional for all wells - enter text only (2500 characers)
- The information provided in these fields can apply to more than one well, so the user must select all the wells to which the descriptions apply.
    - All wells must have the required descriptions before the user can move on.
    - Once a user adds descriptions for well(s), when they click on a well the descriptions fields show what was entered, and all wells that are associated with those descriptions are highlighted on the map.

- If an uploaded document is provided for the description, the database and UI fields contain a link to view/download the uploaded doc.

Acceptable file types

- pdf
- doc, docx 
- jpg, jpeg
- png

(The uploaded doc will be incorporated into the Inventory Report that is generated and sent to Documentum - this will be described in greater detail in a different issue/task)

**Comment by steveoh** [comment]
Is there a list of acceptable doc types or does anything fly?

**Comment by nathankota** [comment]
She has only ever seen pdf and jpg submitted, and the DEQ Documentum system is known to allow those file types (and more), but to avoid potentially receiving unknown or other types that cannot be accesses without specialized software, UIC would like to limit the file upload types to
- pdf
- ms word doc 
- jpg 
- png

**Comment by steveoh** [comment]
> * ms word doc

is that doc and docx?

**Comment by nathankota** [comment]
> > * ms word doc
> 
> is that doc and docx?

yes, those should cover it

**Comment by steveoh** [comment]
I don't see any mention to how much text should be allowed in these fields. I'm going to start with 512 until you tell me otherwise.

**Comment by nathankota** [comment]
> I don't see any mention to how much text should be allowed in these fields. I'm going to start with 512 until you tell me otherwise.

Is that words or characters?

**Comment by steveoh** [comment]
It's characters. I don't know of a database that allows you to set a word count.

**Comment by nathankota** [comment]
2.500 please

**Comment by nathankota** [comment]
Validated as-is. User feedback will be submitted in new issues.
