### ISSUE TITLE
Submit well inventory

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#62]
### [Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457355520677908&cot=14)

When all of the required fields for a Well Inventory are complete (as well as a first-time Site) the user may submit the Well Inventory. 

- Check verification box
- Enter name as signature
- Date of submission auto-populated
- Notification in app UI of successful submission
- Kicks back to the default page - inventory status changes to `Submitted`
- Email to submitter that submission was successful, including a link to the default page
    - includes Site name, well subclass type, date submitted
- Email to Admin that a new submission was made, with a link to the default page
    - includes submitter name, Site name, well subclass type, date submitted

**Comment by nathankota** [comment]
These are the data fields entered by users for all Well Inventories:
| Name on Form | DB field | Domain | Required? | 
| ----------------- | -------- | -------- | :---------: | 
| UIC inventory form order number | UICAuthorization.OrderNumber | n/a | Y | 
| Well Type (selection) | UICWell.WellSubClass | UICWellSubClassDomain | Y |
| Well Construction/Type | UICWell.WellName | n/a | Y | Y |
| Well Operating Status | UICWellOperatingStatus.OperatingStatusType | UICOperatingStatusTypeDomain | Y | Y |
| Number of Wells | UICOperatingStatus.Comments | n/a | Y | |


These are the additional data fields entered by users for SER wells:
| Name on Form | DB field | Domain | Required? | 
| --------------- | -------- | -------- | :---------: | 
| Project Manager | UICContact.ContactName | n/a  | Y |
| Oversight Agency | UICContact.ContactOrganization | UICContactOrganizationDomain | Y |
| Email | UICContact.ContactEmail | n/a | Y |
| Phone | UICContact.ContactPhone | n/a | Y |
| Remediation Type | UICWell.RemediationProjectType | UICRemediationProjectTypeDomain | Y |
| Remediation Project ID | UICWell.RemediationProjectID | n/a | NO |
| Description (if Remediation Type is Other) | UICWell.Comments | n/a | NO |

These are the fields that are not entered by users and are auto-populated:
| Notes | DB field | Domain | Value | Required? | 
| ------ | -------- | -------- | ---------| :---------: | 
| For SER wells' additional (regulatory) contact | UICContact.ContactType | UICContactTypeDomain | 8, DEQ Project Manager | Y |
| To relate to Site | UICWell.AFacility_FK | n/a |   | Y |
| To relate to Authorization table | UICWell.Authorization_FK | n/a |   | Y |
|   | UICWell.WellID | n/a | UTUccwXXXXXXXX where cc=county FIPS; w=well class; X's = last 8 GUID digits | Y |
|   | UICWell.WellClass | UICWellClassDomain | Will always be Class V | Y |
| Defined by #60  | UICWell.WellSWPZ, etc. |  |  | Y |
|   | UICWell.CreatedOn | n/a | Autopopulate when inventory is submitted | Y |
|   | UICWell.HighPriority | UICYesNoUnknownDomain | Autopopulate with "No" | Y |
|   | UICAuthorization.AuthorizationID | n/a | Autopopulate, but not sure of rule for this | Y |
|   | UICAuthorization.AuthorizationType | UICAuthorizationTypeDomain | Autopop with RA | Y |
|   | UICAuthorization.AuthorizationStartDate | n/a | Autopopulate when inventory is submitted | Y |
|   | UICAuthorizationAction.AuthorizationActionType | UICAuthorizationAction | Autopop with NR | Y |
|   | UICWellOperatingStatus.CreatedOn | n/a | Autopopulate when inventory is submitted | Y |

**Comment by steveoh** [comment]
Does this UI work or do you have any suggested changes?

![image](https://user-images.githubusercontent.com/325813/148131290-f723c6ba-e295-464e-bd17-9eebaf342e61.png)

**Comment by nathankota** [comment]
I think it's great. I am trying to show it to UIC folks quickly to see if they have any suggestions but, otherwise, it suits the needs well.

**Comment by nathankota** [comment]
UIC admins also confirmed that the UI is good. I made a slight change to the first comment in this issue about the actions to occur after submission (in italics below):

> When all of the required fields for a Well Inventory are complete (as well as a first-time Site) the user may submit the Well Inventory.
> 
> * Check verification box
> * Enter name as signature
> * Date of submission auto-populated
> * Notification in app UI of successful submission
> * _Kicks back to the default page - inventory status changes to_ `Submitted`
> * Email to submitter that submission was successful, including a link to the default page
>   
>   * includes Site name, well subclass type, date submitted
> * Email to Admin that a new submission was made, with a link to the default page
>   
>   * includes submitter name, Site name, well subclass type, date submitted

**Comment by steveoh** [comment]
Admin email

![image](https://user-images.githubusercontent.com/325813/148309494-874690b0-ce1d-40b0-b606-4f8fdadbfc90.png)

Regulatory user email

![image](https://user-images.githubusercontent.com/325813/148309537-a46062b9-c2b0-454b-bba8-0dcefc5b7e05.png)

**Comment by steveoh** [comment]
Things to note, submitted inventories can be deleted right now. We probably need to refresh on the rules around what you can and can't do now that the site and inventory status are in play.

**Comment by nathankota** [comment]
This is great stuff! I will review it more closely early next week, including altering the rules around deleting submitted inventories. Thank you.

**Comment by nathankota** [comment]
#143 should help with this:
> Things to note, submitted inventories can be deleted right now. We probably need to refresh on the rules around what you can and can't do now that the site and inventory status are in play.

Otherwise, I believe this is good to go!
