### ISSUE TITLE
Delete Well Inventory

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#66]
I would like to be able to delete an **unsubmitted** Well Inventory if I no longer want/need it in my list. If the inventory has been approved by Admin, I cannot delete it.

**Comment by nathankota** [comment]
This works on the UI for unsubmitted well inventories. Will need to test again after #62 is implemented.

**Comment by steveoh** [comment]
We also need to delete any cloud storage items at this time also I would guess.
