### ISSUE TITLE
Check for Site fields managed by UIC db upon import

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#68]
These fields are calculated by [UIC enterprise database Attribute Rules](https://github.com/uic-utah/uic-attribute-rules/blob/master/src/rules/facility.py) and will be assigned a value upon importation.
- `UICFacility.CreatedOn` - created by [editor tracking](https://github.com/uic-utah/uic-attribute-rules/blob/5ae9f8db62ebc712b5d27b31ab5bffc0956b86d9/src/migrations.py#L219-L227)
- `UICFacility.FacilityID`
- `UICFacility.FacilityCity`
- `UICFacility.CountyFIPS`
- `UICFacility.ZipCode` 

Constraints satisfied by data entry into app:
- `UICFacility.FacilityName`
- `UICFacility.FacilityAddress`

**Comment by steveoh** [comment]
What is the task associated with this issue?

**Comment by nathankota** [comment]
I'm still working on defining that. It might just be checking that they happen.

**Comment by steveoh** [comment]
If that is the case, maybe this is better kept as a note rather than an issue?

**Comment by nathankota** [comment]
Added to the [lucid diagram](https://lucid.app/lucidchart/5ad270d8-4aa9-47d9-a66b-8ecfb30d743e/edit?invitationId=inv_02a5a3b4-5dfe-46e5-ad2d-446caaa7dd49&page=0_0#).
