### ISSUE TITLE
Populate UICFacility.CreatedOn 

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#70]
@rsparker-utah can you and Brianna help me understand what this date represents and at what point it should be captured? I thought there was an Attribute Rule for this value to be entered when an inventory is authorized and imported into the UIC enterprise database, but that is not the case.  [The Miro](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457358055859323&cot=10) shows that is should occur when it is created which, I assume, means when the parcel is selected or the Site boundary is digitized. If that is the case, then we will capture CreatedOn in the app database, then push it to the UIC enterprise database when authorized. However, what if a Site boundary is changed once or more before it is submitted? Do we need to know each of those times that it was changed/edited, or just the first time it was created?

**Comment by steveoh** [comment]
This and a few other fields are created by [editor tracking](https://github.com/uic-utah/uic-attribute-rules/blob/5ae9f8db62ebc712b5d27b31ab5bffc0956b86d9/src/migrations.py#L219-L227)
