### ISSUE TITLE
Create space to store application documents

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#73]
For uploaded docs during [well inventory info submission](https://miro.com/app/board/o9J_kjQkE8Y=/?moveToWidget=3074457360333976678&cot=14), and for summary reports of all Site and Well Inventory information that will ultimately be placed in Documentum (either manually or, hopefully, automated if the other DEQ documentum project is successful).

**Comment by steveoh** [comment]
What will be the lifetime of these documents?

**Comment by nathankota** [comment]
I have contacted UIC admin about this.

**Comment by nathankota** [comment]
From Brianna:
_Once the (authorized) inventory is submitted to Documentum I don't think there is a need to also have it in the cloud.  I believe the goal is to have all of our documents that are in documentum available to the public, but I don't think we're there yet.  I also don't think there is a need to keep (documents for) inventories that are not authorized._

**Comment by steveoh** [comment]
Would you decode that to a requirement please

**Comment by nathankota** [comment]
@Brianna81 we will need to be more specific about this as to how/when the documents are removed from storage.

**Comment by nathankota** [comment]
Notes from recent discussion with UIC Team:
Requirements for how the documents are dealt with will depend on whether the integration with Documentum (D2) happens. I have contacted Rachael again. If it does, then the uploaded docs can be deleted/removed after inventory approval and document transfer to D2. Clearer requirements will emerge after upcoming discussions about the approval workflow, and once we know more about D2 integration, in addition to #84.

**Comment by steveoh** [comment]
Don't forget to think about inventories that are never submitted and other cases like that

**Comment by nathankota** [comment]
> Don't forget to think about inventories that are never submitted and other cases like that

New issue will be created to address this.
