### ISSUE TITLE
Check for well fields managed by UIC db upon import

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#75]
`UICWell.Facility_FK`
`UICWell.Authorization_FK`
`UICWell.WellID`
`UICWell.CreatedOn`
`UICWellOperatingStatus.CreatedOn`
`UICAuthorization.AuthorizationID`

**Comment by Brianna81** [comment]
All of these well fields except for the last one are autogenerated by the db. 
UICAuthorization.StartDate is entered by me.  I typically use the date that the form was signed or received.

**Comment by steveoh** [comment]
What is the action to be taken for this issue?

**Comment by nathankota** [comment]
This looks like more of a reminder. I added this to the data transfer area of the [lucid diagram](https://lucid.app/lucidchart/5ad270d8-4aa9-47d9-a66b-8ecfb30d743e/edit?invitationId=inv_02a5a3b4-5dfe-46e5-ad2d-446caaa7dd49&page=0_0#).
