### ISSUE TITLE
Delete user-uploaded files

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#84]
The scenarios where user-uploaded files should be deleted from cloud storage are:

- [x] Admin rejects a submitted inventory
- [x] User deletes an inventory
- [x] User deletes site
- ~(probably a certain time period after an inventory is approved ?)~

**Comment by steveoh** [comment]
Files also should be delete if the user deletes the site or inventory right?

**Comment by nathankota** [comment]
I altered the description to address the comment, but still need to figure out the last bullet point in the description.

> Files also should be delete if the user deletes the site or inventory right?

**Comment by steveoh** [comment]
I suggest creating a new issue for the last checkbox when the details are decided.

**Comment by nathankota** [comment]
> I suggest creating a new issue for the last checkbox when the details are decided.

Working with UIC admins on this, and the case where a draft is never submitted. Otherwise the rest of the scenarios work, as far as can be seen from the UI side.
