### ISSUE TITLE
Persist NAICS subcategories longer

### ISSUE THREAD

**Issue by nathankota** [uic-utah/uic-inventory#98]
> When using the NAICS code helper button...drilling down to get your code, on the last click, the options come up, shown as blue boxes (everything that's included in that subcatergory) but then they quickly disappear, and you're directed back to where your NAICS code is entered.  Those subcategories need to stay up long enough to read to ensure that they have selected the correct one.

![image](https://user-images.githubusercontent.com/15659642/136453435-1bd3b4de-64b5-44a6-9642-a99e8d42bf64.png)

**Comment by steveoh** [comment]
The title comes from the last selection (before the blue items), none of items on this page influence anything the app stores.

**Comment by nathankota** [comment]
Huh...it appears to save the last selection. This is the same Site after using the NAICS selector to first let the last page disappear without selecting anything, then selecting something on that final page:

![image](https://user-images.githubusercontent.com/15659642/136461445-1660a3a8-1496-4e52-9353-ae20e7db1364.png)

vs
  
![image](https://user-images.githubusercontent.com/15659642/136461260-c99900e3-bc90-4f8b-b40d-b78b46f5259c.png)

**Comment by nathankota** [comment]
they like the specific title

**Comment by steveoh** [comment]
Then i will make the dialog stay open until they choose one.

**Comment by nathankota** [comment]
Yes, that would work well, and also highlight the selection. In the image below, I clicked `Passenger railways, line-haul` and you can see that it populated the NAICS title field, but there is no indication that it was selected in the dialog.

![image](https://user-images.githubusercontent.com/15659642/138278188-a788de39-344c-4814-a96e-4349efe7e2e4.png)

**Comment by nathankota** [comment]
Please also highlight the final selection so user knows which item they have chosen before they click `Select`.

**Comment by nathankota** [comment]
looks great, thank you!
